/**
 * Expanded Replacement Behavior Seed Library
 * ───────────────────────────────────────────
 * Covers all 4 functions × 3 age bands × 3 settings.
 */

import type { ReplacementBehavior } from './dal';

export const SEED_LIBRARY: ReplacementBehavior[] = [
  // ─── ATTENTION ─────────────────────────────────────
  // Early Childhood
  { id: 'a-ec-h', trigger: 'Crying for adult attention at home', function: 'attention', ageBand: 'early-childhood', setting: 'home', commLevel: 'pre-verbal',
    definition: 'Child cries or whines to get caregiver attention when adult is busy.',
    teachingSteps: ['Model tapping adult\'s arm', 'Practice during calm moments', 'Prompt when crying starts', 'Fade prompts over time'],
    prompts: ['Hand-over-hand arm tap', 'Gesture toward adult', 'Verbal: "Touch my arm"'],
    reinforcement: 'Immediately respond to arm tap. "You got my attention! Great job!"',
    generalization: 'Practice with different caregivers and rooms.' },
  { id: 'a-ec-s', trigger: 'Calling out in preschool circle time', function: 'attention', ageBand: 'early-childhood', setting: 'school', commLevel: 'emerging',
    definition: 'Child calls out or makes noises to get teacher attention during group instruction.',
    teachingSteps: ['Teach hand-raise', 'Practice with visual cue card', 'Praise hand-raising immediately', 'Planned ignoring for call-outs'],
    prompts: ['Point to hand-raise visual', 'Verbal: "Show me quiet hand"', 'Model hand-raise'],
    reinforcement: 'Respond quickly to raised hand. "I love how you waited!"',
    generalization: 'Use at mealtimes and during play.' },
  { id: 'a-ec-c', trigger: 'Tantrums in public for attention', function: 'attention', ageBand: 'early-childhood', setting: 'community', commLevel: 'emerging',
    definition: 'Child tantrums in stores or public to get parent to engage.',
    teachingSteps: ['Pre-teach "say my name"', 'Give a helper job', 'Schedule check-ins during outings', 'Praise appropriate bids'],
    prompts: ['Verbal: "Say mama/dada"', 'Offer a counting task', 'Give a visual timer for wait'],
    reinforcement: 'Respond to name-calling: "You said my name! What do you need?"',
    generalization: 'Grocery stores, restaurants, parks.' },

  // School Age
  { id: 'a-sa-h', trigger: 'Constant interrupting at home', function: 'attention', ageBand: 'school-age', setting: 'home', commLevel: 'verbal',
    definition: 'Child interrupts conversations to get immediate adult attention.',
    teachingSteps: ['Teach "excuse me" + wait', 'Use a visual signal (hand on shoulder)', 'Practice turn-taking', 'Acknowledge waiting'],
    prompts: ['Verbal: "Say excuse me"', 'Point to wait signal', 'Nonverbal: hold up finger'],
    reinforcement: '"Thank you for waiting! What did you need?"',
    generalization: 'Phone calls, sibling interactions, guest visits.' },
  { id: 'a-sa-s', trigger: 'Calling out in classroom', function: 'attention', ageBand: 'school-age', setting: 'school', commLevel: 'verbal',
    definition: 'Student calls out or makes noises to get teacher attention.',
    teachingSteps: ['Teach hand-raising or signal', 'Give attention for appropriate bids', 'Use planned ignoring for call-outs', 'Set up check-in schedule'],
    prompts: ['Point to hand-raise visual', 'Verbal: "Raise your hand"', 'Thumbs up when hand raised'],
    reinforcement: '"Thank you for raising your hand!" Respond quickly.',
    generalization: 'Practice at home with dinner table signal.' },
  { id: 'a-sa-c', trigger: 'Acting silly in public', function: 'attention', ageBand: 'school-age', setting: 'community', commLevel: 'verbal',
    definition: 'Child acts silly or clownish in community to get peer/adult attention.',
    teachingSteps: ['Pre-teach appropriate conversation starters', 'Role-play greetings', 'Give "attention budget" (3 jokes, then focus)', 'Praise appropriate social bids'],
    prompts: ['Verbal: "What\'s a good way to start?"', 'Cue card with conversation starters'],
    reinforcement: '"That was a great way to talk to them!"',
    generalization: 'Restaurants, sports, family gatherings.' },

  // Adolescent
  { id: 'a-ad-h', trigger: 'Arguing to keep parent engaged', function: 'attention', ageBand: 'adolescent', setting: 'home', commLevel: 'verbal',
    definition: 'Teen argues or debates to maintain adult engagement and attention.',
    teachingSteps: ['Teach "scheduled talk time"', 'Set up daily check-in (10 min)', 'Disengage from arguments calmly', 'Reinforce appropriate conversation'],
    prompts: ['Verbal: "Let\'s talk about this at check-in"', 'Timer for talk time'],
    reinforcement: '"I appreciate you sharing that with me during our time."',
    generalization: 'Car rides, meal times, evening routine.' },
  { id: 'a-ad-s', trigger: 'Disruptive behavior in class for peer attention', function: 'attention', ageBand: 'adolescent', setting: 'school', commLevel: 'verbal',
    definition: 'Teen disrupts class to get peer laughter or reactions.',
    teachingSteps: ['Assign class helper role', 'Private praise for on-task behavior', 'Peer mentor pairing', 'After-class check-ins'],
    prompts: ['Private signal to redirect', 'Written note', 'Brief hallway check-in'],
    reinforcement: '"I noticed you stayed focused today. That takes maturity."',
    generalization: 'Assemblies, group projects, lunch.' },
  { id: 'a-ad-c', trigger: 'Attention-seeking in community', function: 'attention', ageBand: 'adolescent', setting: 'community', commLevel: 'verbal',
    definition: 'Teen engages in loud or inappropriate behavior in public for social attention.',
    teachingSteps: ['Pre-teach social expectations', 'Role-play scenarios', 'Give structured social role', 'Debrief after outings'],
    prompts: ['Verbal cue: "How are we showing up?"', 'Discrete signal'],
    reinforcement: '"You handled that really maturely."',
    generalization: 'Mall, sports events, family outings.' },

  // ─── ESCAPE ────────────────────────────────────────
  // Early Childhood
  { id: 'e-ec-h', trigger: 'Hitting when frustrated by tasks', function: 'escape', ageBand: 'early-childhood', setting: 'home', commLevel: 'emerging',
    definition: 'Child hits to escape demands like cleanup or getting dressed.',
    teachingSteps: ['Teach "break" card or gesture', 'Practice during calm moments', 'Prompt when frustration begins', 'Fade prompts over time'],
    prompts: ['Hand-over-hand to use break card', 'Point to break card', 'Verbal: "Use your card"'],
    reinforcement: 'Honor break request. "Great job asking for a break!"',
    generalization: 'Practice in multiple rooms with different caregivers.' },
  { id: 'e-ec-s', trigger: 'Flopping during transitions at school', function: 'escape', ageBand: 'early-childhood', setting: 'school', commLevel: 'pre-verbal',
    definition: 'Child drops to floor during transitions to avoid next activity.',
    teachingSteps: ['Use visual schedule', 'Give transition warnings (timer)', 'Offer choice of how to transition', 'Reinforce walking to next activity'],
    prompts: ['Show visual schedule', 'Count down: "3, 2, 1, let\'s go"', 'Offer hand or buddy'],
    reinforcement: '"You walked all by yourself! High five!"',
    generalization: 'Home transitions, community outings.' },
  { id: 'e-ec-c', trigger: 'Crying to leave store', function: 'escape', ageBand: 'early-childhood', setting: 'community', commLevel: 'emerging',
    definition: 'Child cries or tantrums to escape community settings.',
    teachingSteps: ['Pre-teach visual shopping list', 'Use timer: "5 more minutes"', 'Teach "all done" sign', 'Gradual exposure to longer trips'],
    prompts: ['Show "all done" card', 'Verbal: "Almost done, one more thing"'],
    reinforcement: '"You stayed with me the whole time! You earned a sticker!"',
    generalization: 'Different stores, waiting rooms, restaurants.' },

  // School Age
  { id: 'e-sa-h', trigger: 'Refusing homework', function: 'escape', ageBand: 'school-age', setting: 'home', commLevel: 'verbal',
    definition: 'Child refuses or argues to avoid homework tasks.',
    teachingSteps: ['Break tasks into chunks', 'Teach "I need help" phrase', 'First/then board', 'Timer for work periods'],
    prompts: ['Verbal: "What part is hard?"', 'Point to first/then', 'Offer choice of where to start'],
    reinforcement: '"You did 10 minutes of focused work! Break time!"',
    generalization: 'Chores, reading time, practice activities.' },
  { id: 'e-sa-s', trigger: 'Running away during transitions', function: 'escape', ageBand: 'school-age', setting: 'school', commLevel: 'verbal',
    definition: 'Child runs from area when asked to transition to less preferred activity.',
    teachingSteps: ['Use visual timer warnings', 'Teach "I need a minute"', 'Offer choice of how to transition', 'Reduce transition time gradually'],
    prompts: ['Show visual timer', 'Verbal: "What can you say?"', 'Gesture toward area'],
    reinforcement: '"You handled that transition so well!" Offer preferred activity after.',
    generalization: 'Hallways, cafeteria, home.' },
  { id: 'e-sa-c', trigger: 'Hiding in community settings', function: 'escape', ageBand: 'school-age', setting: 'community', commLevel: 'verbal',
    definition: 'Child hides or wanders to escape structured community activities.',
    teachingSteps: ['Pre-teach expectations', 'Create escape plan (ask for break)', 'Use social story', 'Gradual exposure'],
    prompts: ['Verbal: "Need a break? Ask me"', 'Show break card', 'Check-in every 10 min'],
    reinforcement: '"You stayed and asked for a break! That was so responsible."',
    generalization: 'Church, sports, birthday parties.' },

  // Adolescent
  { id: 'e-ad-h', trigger: 'Shutting down to avoid chores', function: 'escape', ageBand: 'adolescent', setting: 'home', commLevel: 'verbal',
    definition: 'Teen shuts down, goes to room, or ignores requests to avoid household tasks.',
    teachingSteps: ['Negotiate chore schedule together', 'Offer choice of when to do it', 'Break into smaller steps', 'Natural consequences for completion'],
    prompts: ['Verbal: "When would you like to do this?"', 'Written checklist', 'Timer option'],
    reinforcement: '"Thanks for getting that done. The rest of the evening is yours."',
    generalization: 'School assignments, personal hygiene, meal prep.' },
  { id: 'e-ad-s', trigger: 'Skipping class to avoid work', function: 'escape', ageBand: 'adolescent', setting: 'school', commLevel: 'verbal',
    definition: 'Teen leaves class or avoids attending to escape academic demands.',
    teachingSteps: ['Identify hardest subjects', 'Set up tutoring/support', 'Self-advocacy training', 'Modified assignments when appropriate'],
    prompts: ['Check-in at start of class', 'Self-monitoring sheet', 'Signal for help'],
    reinforcement: '"You stayed the whole period. That takes real effort."',
    generalization: 'Testing situations, group work, presentations.' },
  { id: 'e-ad-c', trigger: 'Refusing to participate in activities', function: 'escape', ageBand: 'adolescent', setting: 'community', commLevel: 'verbal',
    definition: 'Teen refuses to engage in social or community activities.',
    teachingSteps: ['Co-plan activities', 'Offer structured role', 'Set time limit', 'Debrief after'],
    prompts: ['Verbal: "You pick how long we stay"', 'Text check-ins'],
    reinforcement: '"I appreciate you giving it a try."',
    generalization: 'Family events, volunteering, sports.' },

  // ─── TANGIBLE ──────────────────────────────────────
  // Early Childhood
  { id: 't-ec-h', trigger: 'Screaming for items at home', function: 'tangible', ageBand: 'early-childhood', setting: 'home', commLevel: 'pre-verbal',
    definition: 'Child screams or cries to obtain desired items.',
    teachingSteps: ['Model pointing or signing "want"', 'Wait for calm before giving', 'First/then language', 'Reinforce approximations'],
    prompts: ['Physical prompt to point', 'Model sign', 'Verbal: "Show me"'],
    reinforcement: '"You asked so nicely!" Give item immediately.',
    generalization: 'Mealtimes, play, stores.' },
  { id: 't-ec-s', trigger: 'Grabbing toys from peers', function: 'tangible', ageBand: 'early-childhood', setting: 'school', commLevel: 'emerging',
    definition: 'Child snatches toys from peers rather than asking.',
    teachingSteps: ['Teach "my turn please"', 'Use turn-taking timer', 'Practice with preferred toys', 'Praise trading'],
    prompts: ['Model the phrase', 'Gesture toward timer', 'Verbal: "What do you say?"'],
    reinforcement: '"You asked for a turn! Here you go!"',
    generalization: 'Playground, home with siblings, playdates.' },
  { id: 't-ec-c', trigger: 'Tantrum in store for items', function: 'tangible', ageBand: 'early-childhood', setting: 'community', commLevel: 'emerging',
    definition: 'Child tantrums in stores to get desired items.',
    teachingSteps: ['Pre-teach: "We\'re getting X today"', 'Visual shopping list', 'Teach "maybe later" tolerance', 'Offer choice within budget'],
    prompts: ['Show shopping list', 'Verbal: "That\'s not on our list today"', 'Redirect to helper task'],
    reinforcement: '"You didn\'t ask for extra things! You earned a sticker!"',
    generalization: 'Different stores, restaurants, outings.' },

  // School Age
  { id: 't-sa-h', trigger: 'Arguing for screen time', function: 'tangible', ageBand: 'school-age', setting: 'home', commLevel: 'verbal',
    definition: 'Child argues, negotiates, or has meltdowns over screen time access.',
    teachingSteps: ['Create visual schedule with screen time', 'Teach "when can I have it?" phrase', 'First/then: "First homework, then screen"', 'Use timer for transitions'],
    prompts: ['Point to schedule', 'Verbal: "Check your schedule"', 'Timer warning'],
    reinforcement: '"You waited until screen time! Enjoy!"',
    generalization: 'Other preferred activities, outings.' },
  { id: 't-sa-s', trigger: 'Taking classmates\' supplies', function: 'tangible', ageBand: 'school-age', setting: 'school', commLevel: 'verbal',
    definition: 'Child takes others\' supplies or materials without asking.',
    teachingSteps: ['Teach "can I borrow…?"', 'Role-play borrowing scenarios', 'Provide own supply kit', 'Praise appropriate requests'],
    prompts: ['Verbal: "How do we ask?"', 'Cue card', 'Point to supply bin'],
    reinforcement: '"You asked to borrow that! Great problem-solving!"',
    generalization: 'Home, playdates, community.' },
  { id: 't-sa-c', trigger: 'Begging for purchases while out', function: 'tangible', ageBand: 'school-age', setting: 'community', commLevel: 'verbal',
    definition: 'Child begs, whines, or escalates to get items while shopping.',
    teachingSteps: ['Set expectations before outing', 'Teach saving/earning system', 'Offer one approved choice', 'Practice accepting "not today"'],
    prompts: ['Verbal: "Remember our agreement"', 'Visual reminder card'],
    reinforcement: '"You accepted \'not today\' so maturely! Let\'s plan for next time."',
    generalization: 'Online shopping, birthday wishlists.' },

  // Adolescent
  { id: 't-ad-h', trigger: 'Demanding phone/device access', function: 'tangible', ageBand: 'adolescent', setting: 'home', commLevel: 'verbal',
    definition: 'Teen escalates when device access is restricted.',
    teachingSteps: ['Co-create device agreement', 'Teach negotiation skills', 'Scheduled device times', 'Natural consequences for misuse'],
    prompts: ['Reference agreement', 'Verbal: "What does our contract say?"'],
    reinforcement: '"You followed the agreement all week. Extra 30 min this weekend."',
    generalization: 'Car privileges, spending money, social outings.' },
  { id: 't-ad-s', trigger: 'Pressuring peers to share/give items', function: 'tangible', ageBand: 'adolescent', setting: 'school', commLevel: 'verbal',
    definition: 'Teen pressures or manipulates peers for items.',
    teachingSteps: ['Teach respectful requesting', 'Social skills group', 'Role-play appropriate trading', 'Self-reflection on impact'],
    prompts: ['Private conversation', 'Written reflection', 'Peer feedback'],
    reinforcement: '"I noticed you respected their answer. That builds trust."',
    generalization: 'Online interactions, family dynamics.' },
  { id: 't-ad-c', trigger: 'Stealing or taking items in community', function: 'tangible', ageBand: 'adolescent', setting: 'community', commLevel: 'verbal',
    definition: 'Teen takes items without paying or asking in community settings.',
    teachingSteps: ['Discuss natural/legal consequences', 'Earning system for desired items', 'Impulse control strategies', 'Community service/restitution'],
    prompts: ['Pre-teach before outing', 'Check-in signal', 'Budget planning'],
    reinforcement: '"You saved up and bought it yourself. That\'s real independence."',
    generalization: 'Online purchases, friend dynamics.' },

  // ─── SENSORY ───────────────────────────────────────
  // Early Childhood
  { id: 's-ec-h', trigger: 'Repetitive rocking or hand-flapping', function: 'sensory', ageBand: 'early-childhood', setting: 'home', commLevel: 'pre-verbal',
    definition: 'Child engages in self-stimulatory behavior for sensory input.',
    teachingSteps: ['Identify sensory need', 'Offer appropriate alternative', 'Schedule sensory breaks', 'Redirect without punishment'],
    prompts: ['Offer fidget tool', 'Guide to sensory area', 'Verbal: "Sensory break"'],
    reinforcement: '"I love how you used your fidget!" Allow sensory breaks.',
    generalization: 'Keep sensory tools in all settings.' },
  { id: 's-ec-s', trigger: 'Covering ears in noisy classroom', function: 'sensory', ageBand: 'early-childhood', setting: 'school', commLevel: 'emerging',
    definition: 'Child covers ears, cries, or withdraws during loud activities.',
    teachingSteps: ['Provide noise-canceling headphones', 'Create quiet corner', 'Teach "too loud" card', 'Gradual exposure with support'],
    prompts: ['Offer headphones', 'Point to quiet corner', 'Visual: "too loud" card'],
    reinforcement: '"You used your headphones! You found a solution!"',
    generalization: 'Assemblies, cafeteria, community events.' },
  { id: 's-ec-c', trigger: 'Meltdown from sensory overload in stores', function: 'sensory', ageBand: 'early-childhood', setting: 'community', commLevel: 'pre-verbal',
    definition: 'Child has meltdown from lights, sounds, or crowds in public.',
    teachingSteps: ['Plan short outings first', 'Bring sensory kit (headphones, chewy)', 'Identify quiet zones', 'Use stroller/carrier as safe space'],
    prompts: ['Offer chewy or squeeze toy', 'Move to quieter area', 'Deep pressure hug'],
    reinforcement: '"You used your chewy! That helped you feel better."',
    generalization: 'Different stores, events, restaurants.' },

  // School Age
  { id: 's-sa-h', trigger: 'Chewing on clothing or objects', function: 'sensory', ageBand: 'school-age', setting: 'home', commLevel: 'verbal',
    definition: 'Child chews on shirt collars, pencils, or objects for oral input.',
    teachingSteps: ['Provide chew necklace/tube', 'Offer crunchy snacks during work', 'Teach self-monitoring', 'Replace items gradually'],
    prompts: ['Offer chew tool', 'Verbal: "Need your chewy?"', 'Visual reminder'],
    reinforcement: '"You used your chew tube instead! Great choice."',
    generalization: 'School, car rides, community.' },
  { id: 's-sa-s', trigger: 'Fidgeting and can\'t sit still in class', function: 'sensory', ageBand: 'school-age', setting: 'school', commLevel: 'verbal',
    definition: 'Child fidgets, bounces, or moves constantly during seated activities.',
    teachingSteps: ['Provide fidget tool or wobble cushion', 'Movement breaks every 20 min', 'Standing desk option', 'Teach body check-in'],
    prompts: ['Offer fidget', 'Verbal: "Time for a body break"', 'Point to movement menu'],
    reinforcement: '"You did your body break and came right back. Awesome!"',
    generalization: 'Home homework time, church, restaurants.' },
  { id: 's-sa-c', trigger: 'Avoiding certain textures or foods', function: 'sensory', ageBand: 'school-age', setting: 'community', commLevel: 'verbal',
    definition: 'Child avoids specific textures in clothing, food, or environment.',
    teachingSteps: ['Gradual exposure (look → touch → try)', 'Offer choices within category', 'Respect boundaries while expanding', 'Pair new with preferred'],
    prompts: ['Verbal: "Just touch it first"', 'Offer choice: "This one or that one?"'],
    reinforcement: '"You tried something new! How brave!"',
    generalization: 'Restaurants, friend\'s houses, school cafeteria.' },

  // Adolescent
  { id: 's-ad-h', trigger: 'Excessive screen use for sensory regulation', function: 'sensory', ageBand: 'adolescent', setting: 'home', commLevel: 'verbal',
    definition: 'Teen uses screens excessively as primary sensory regulation strategy.',
    teachingSteps: ['Identify underlying sensory need', 'Offer alternative regulation (music, exercise)', 'Co-create media plan', 'Teach self-monitoring'],
    prompts: ['Verbal: "What feeling are you trying to get?"', 'Offer alternatives menu'],
    reinforcement: '"You went for a walk instead. How did that feel?"',
    generalization: 'School breaks, waiting situations, before bed.' },
  { id: 's-ad-s', trigger: 'Leaving class due to sensory overwhelm', function: 'sensory', ageBand: 'adolescent', setting: 'school', commLevel: 'verbal',
    definition: 'Teen leaves classroom when sensory input becomes overwhelming.',
    teachingSteps: ['Create sensory profile', 'Designated calm space/pass', 'Self-advocacy: "I need a sensory break"', 'Noise-canceling earbuds'],
    prompts: ['Break pass', 'Self-monitoring checklist', 'Verbal: "Use your pass"'],
    reinforcement: '"You used your pass and came back. That\'s real self-awareness."',
    generalization: 'Assemblies, cafeteria, community.' },
  { id: 's-ad-c', trigger: 'Avoiding social events due to sensory issues', function: 'sensory', ageBand: 'adolescent', setting: 'community', commLevel: 'verbal',
    definition: 'Teen avoids social gatherings due to noise, crowds, or sensory overload.',
    teachingSteps: ['Plan exit strategy together', 'Bring regulation tools', 'Set time limits', 'Gradual exposure with support'],
    prompts: ['Pre-plan: "When will we check in?"', 'Signal for break', 'Fidget/earbud kit'],
    reinforcement: '"You stayed for an hour and managed it well. I\'m proud of you."',
    generalization: 'Family events, dances, sporting events.' },
];
