/**
 * Behavior Lab - All 30 Game Definitions (local JSON)
 */
import type { LabGameConfig } from './lab-types';

export const LAB_GAMES: LabGameConfig[] = [
  // STAGE 1 - FOUNDATIONS
  {
    id: 'function_flash', title: 'Function Flash', stage: 1, difficulty: 'easy', difficulty_dots: 1,
    skill_tags: ['functions'], est_seconds: 90,
    goal: 'Identify the most likely function quickly.',
    micro_tip: 'Look at what changed after the behavior - what did it help them get or avoid?',
    screens: { intro: { headline: 'Function Flash', body: 'Practice spotting the behavior\'s job in fast, real-life moments.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child screams "Look at me!" while parent is on the phone.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Attention', explain: 'The child is trying to get the parent\'s attention away from the phone.' },
      { scenario: 'Student puts head down when math worksheet is placed on desk.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'The behavior happens when a demand is presented - likely trying to avoid the task.' },
      { scenario: 'Toddler throws cup on the floor and watches it fall repeatedly.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'The behavior happens repeatedly for the visual/auditory input - no social consequence needed.' },
      { scenario: 'Child grabs sibling\'s tablet and runs away.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Access', explain: 'The child gains access to a preferred item (the tablet).' },
      { scenario: 'Teen slams door after being told to do chores.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'The door slam follows a demand (chores), and the teen removes themselves from the situation.' },
      { scenario: 'Child cries loudly until parent picks them up.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Attention', explain: 'Crying produces adult interaction (being picked up, comforted).' },
      { scenario: 'Student calls out answers without raising hand. Teacher responds each time.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Attention', explain: 'Calling out reliably produces teacher attention (even if corrective).' },
      { scenario: 'Child rocks back and forth while sitting alone waiting.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'Rocking happens without social consequences - likely provides sensory input.' },
      { scenario: 'Learner tantrums at store until parent buys candy.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Access', explain: 'The tantrum results in gaining a preferred item (candy).' },
      { scenario: 'Child hides under table when guest arrives.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'The child removes themselves from a social situation - avoiding the interaction.' },
    ],
  },
  {
    id: 'reinforcement_radar', title: 'Reinforcement Radar', stage: 1, difficulty: 'easy-med', difficulty_dots: 2,
    skill_tags: ['reinforcement', 'consequences'], est_seconds: 120,
    goal: 'Decide whether the consequence likely strengthened the behavior.',
    micro_tip: 'If it worked (got relief, attention, or access), the brain may repeat it.',
    screens: { intro: { headline: 'Reinforcement Radar', body: 'Practice spotting when a consequence might accidentally strengthen behavior.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child whines for a snack. Parent says no, then gives in 5 minutes later.', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Likely reinforced', explain: 'The child got the snack after whining - brain learns: whining works (eventually).' },
      { scenario: 'Student yells in class. Teacher ignores and continues teaching without looking.', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Unlikely reinforced', explain: 'No attention was delivered. If function was attention, the behavior was not reinforced this time.' },
      { scenario: 'Child throws toy. Parent says "We don\'t throw!" and picks it up.', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Likely reinforced', explain: 'Throwing produced attention (verbal + physical interaction). Even correction is attention.' },
      { scenario: 'Teen refuses homework. Parent argues for 10 minutes, then says "Fine, skip it."', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Likely reinforced', explain: 'Refusal ultimately removed the homework demand AND produced attention.' },
      { scenario: 'Child hits sibling. Parent calmly separates them with no verbal reaction and redirects.', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Maybe', explain: 'Separation could function as escape from sibling interaction. Depends on the function.' },
      { scenario: 'Student completes worksheet quickly. Teacher gives a sticker.', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Likely reinforced', explain: 'Positive consequence (sticker) delivered after desired behavior - reinforcement.' },
      { scenario: 'Child asks nicely for iPad. Parent says "Not right now" and holds firm.', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Unlikely reinforced', explain: 'The request did not produce the item. The appropriate request was not reinforced here.' },
      { scenario: 'Learner elopes from circle time. Aide chases and carries them back.', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Likely reinforced', explain: 'Elopement produced 1-on-1 attention + potential escape from group. Both may reinforce.' },
      { scenario: 'Child screams at bedtime. Parent stays and rubs their back for 20 minutes.', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Likely reinforced', explain: 'Screaming produced extended parent attention and physical comfort.' },
      { scenario: 'Student raises hand and waits. Teacher calls on someone else.', options: ['Likely reinforced', 'Maybe', 'Unlikely reinforced'], answer: 'Unlikely reinforced', explain: 'The desired behavior (hand-raising) did not produce the expected consequence.' },
    ],
  },
  {
    id: 'escape_or_attention', title: 'Escape or Attention?', stage: 1, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['functions'], est_seconds: 120,
    goal: 'Discriminate Escape/Avoid vs Attention.',
    micro_tip: 'Ask: Did something stop (escape) or did interaction increase (attention)?',
    screens: { intro: { headline: 'Escape or Attention?', body: 'These two can feel similar. Learn the key difference fast.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child cries when told to brush teeth. Parent says "Fine, skip it tonight."', options: ['Escape/Avoid', 'Attention'], answer: 'Escape/Avoid', explain: 'The demand (brushing teeth) was removed. The behavior produced escape.' },
      { scenario: 'Child makes silly faces during dinner. Everyone laughs.', options: ['Escape/Avoid', 'Attention'], answer: 'Attention', explain: 'The behavior produces interaction and laughter - attention.' },
      { scenario: 'Student says "I feel sick" every time spelling test starts. Goes to nurse.', options: ['Escape/Avoid', 'Attention'], answer: 'Escape/Avoid', explain: 'The behavior consistently removes the student from the testing demand.' },
      { scenario: 'Child interrupts parent\'s conversation with friend repeatedly.', options: ['Escape/Avoid', 'Attention'], answer: 'Attention', explain: 'Interrupting redirects parent\'s attention from friend to child.' },
      { scenario: 'Teen throws backpack and storms to room when asked about homework.', options: ['Escape/Avoid', 'Attention'], answer: 'Escape/Avoid', explain: 'The teen physically removes themselves from the homework conversation.' },
      { scenario: 'Child says mean things to sibling. Parent lectures for 5 minutes.', options: ['Escape/Avoid', 'Attention'], answer: 'Attention', explain: 'The 5-minute lecture is sustained 1-on-1 attention (even if negative).' },
      { scenario: 'Learner covers ears and hums when given a direction.', options: ['Escape/Avoid', 'Attention'], answer: 'Escape/Avoid', explain: 'Covering ears blocks the demand. If adults back off, escape is reinforced.' },
      { scenario: 'Child pretends to be hurt and cries. Parent rushes over to check.', options: ['Escape/Avoid', 'Attention'], answer: 'Attention', explain: 'Faking injury reliably produces urgent parental attention.' },
      { scenario: 'Student takes a long time in the bathroom during math class.', options: ['Escape/Avoid', 'Attention'], answer: 'Escape/Avoid', explain: 'Extended bathroom time removes the student from the academic demand.' },
      { scenario: 'Child drops food on the floor and watches parent\'s reaction.', options: ['Escape/Avoid', 'Attention'], answer: 'Attention', explain: 'The child watches for the reaction - the social response is the payoff.' },
    ],
  },
  {
    id: 'access_or_attention', title: 'Access or Attention?', stage: 1, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['functions'], est_seconds: 120,
    goal: 'Distinguish Access from Attention.',
    micro_tip: 'Access is bigger than objects - it can be activities, control, or choices.',
    screens: { intro: { headline: 'Access or Attention?', body: 'Practice telling "I want you" vs "I want that" apart.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child tantrums when told to turn off the TV.', options: ['Attention', 'Access'], answer: 'Access', explain: 'The tantrum is about regaining the TV (a preferred activity), not about interaction.' },
      { scenario: 'Child tugs on parent\'s sleeve until they stop talking to neighbor.', options: ['Attention', 'Access'], answer: 'Attention', explain: 'The child wants the parent\'s focus, not an object or activity.' },
      { scenario: 'Learner cries when another child picks the red crayon first.', options: ['Attention', 'Access'], answer: 'Access', explain: 'The crying is about the specific item (red crayon), not about adult interaction.' },
      { scenario: 'Child makes loud noises until parent looks up from phone.', options: ['Attention', 'Access'], answer: 'Attention', explain: 'The goal is the parent\'s eyes and engagement, not a tangible item.' },
      { scenario: 'Teen refuses to eat unless they can pick the restaurant.', options: ['Attention', 'Access'], answer: 'Access', explain: 'This is about access to choice/control, not about getting adult attention.' },
      { scenario: 'Child shows parent every drawing, one at a time.', options: ['Attention', 'Access'], answer: 'Attention', explain: 'The child wants acknowledgment and interaction - social reinforcement.' },
      { scenario: 'Learner reaches across the table to grab peer\'s snack.', options: ['Attention', 'Access'], answer: 'Access', explain: 'The behavior directly produces a tangible item.' },
      { scenario: 'Child says "Watch this!" before jumping off the couch.', options: ['Attention', 'Access'], answer: 'Attention', explain: '"Watch this!" explicitly requests someone to observe - attention-seeking.' },
      { scenario: 'Student argues until allowed to use the computer instead of writing.', options: ['Attention', 'Access'], answer: 'Access', explain: 'Arguing produces access to a preferred activity (computer over writing).' },
      { scenario: 'Child stands between parent and sibling during story time.', options: ['Attention', 'Access'], answer: 'Attention', explain: 'The child is seeking proximity and exclusive parent attention.' },
    ],
  },
  {
    id: 'sensory_or_escape', title: 'Sensory or Escape?', stage: 1, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['functions'], est_seconds: 120,
    goal: 'Distinguish sensory from escape.',
    micro_tip: 'Sensory behavior often happens even without an audience.',
    screens: { intro: { headline: 'Sensory or Escape?', body: 'Is this about the body or about getting out of something?', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child hums and rocks while alone in their room, even when nobody responds.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'Happens without social consequence - automatic reinforcement.' },
      { scenario: 'Student puts hoodie over head when fluorescent lights buzz loudly.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'The behavior blocks aversive sensory input (buzzing light).' },
      { scenario: 'Child says "I can\'t do it" and pushes worksheet away.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'The behavior directly follows a task demand and aims to remove it.' },
      { scenario: 'Learner chews on shirt collar throughout the day, in every setting.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'Chewing happens across settings without social triggers - likely oral sensory need.' },
      { scenario: 'Child cries and runs away when hair-brushing starts.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'Running away removes the aversive activity. Could also have sensory components, but functions to escape the demand.' },
      { scenario: 'Student spins in circles on the playground by themselves.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'Spinning alone provides vestibular input - no social consequence needed.' },
      { scenario: 'Child refuses to enter the noisy cafeteria and sits in the hallway.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'While noise may be aversive (sensory), the function is escaping the environment.' },
      { scenario: 'Learner taps pencil rhythmically during independent work, even when alone.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'Rhythmic tapping persists without social reinforcement - auditory/tactile input.' },
      { scenario: 'Teen says "This is stupid" and leaves the room when homework gets hard.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'Leaving removes the difficult task - escape from academic demand.' },
      { scenario: 'Child picks at skin on fingers during quiet activities, even when calm.', options: ['Escape/Avoid', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'Skin-picking happens during calm moments without demands - automatic reinforcement.' },
    ],
  },
  {
    id: 'consequence_match', title: 'Consequence Match', stage: 1, difficulty: 'easy-med', difficulty_dots: 2,
    skill_tags: ['functions', 'consequences'], est_seconds: 120,
    goal: 'Match consequences to what they provide.',
    micro_tip: 'A consequence teaches the brain what works - whether we meant to or not.',
    screens: { intro: { headline: 'Consequence Match', body: 'Map what happens after behavior to the function it provides.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Parent scolds child for 3 minutes after hitting.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Attention', explain: '3 minutes of scolding is 3 minutes of 1-on-1 attention.' },
      { scenario: 'Teacher removes worksheet after student cries.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'The demand was removed - escape was delivered.' },
      { scenario: 'Parent gives child the iPad to stop screaming in the car.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Access', explain: 'Screaming produced a preferred item (iPad).' },
      { scenario: 'Child sent to room with toys after meltdown.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'Being sent away removes the situation - even if the room has toys, it functions as escape from the demand.' },
      { scenario: 'Parent hugs and rocks child after biting.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Attention', explain: 'Physical comfort after problem behavior = attention + possibly sensory input.' },
      { scenario: 'Child allowed to skip dinner vegetables after gagging.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'Gagging removed the non-preferred food demand.' },
      { scenario: 'Learner gets to choose the game after finishing a hard task.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Access', explain: 'Completing the task produced access to a preferred activity.' },
      { scenario: 'Child given a chewy tube after biting their shirt.', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'The chewy tube addresses the same oral sensory need as shirt-biting.' },
    ],
  },
  {
    id: 'abc_builder', title: 'ABC Builder', stage: 1, difficulty: 'easy', difficulty_dots: 1,
    skill_tags: ['abc'], est_seconds: 120,
    goal: 'Build a clean ABC from a story.',
    micro_tip: 'Keep B observable: "threw iPad" instead of "got mad."',
    screens: { intro: { headline: 'ABC Builder', body: 'Practice turning moments into clear, usable ABC notes.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Story: Mom says "Time for bath." Child screams and throws toy. Mom says "OK, 5 more minutes."', prompt: 'What is the Antecedent?', options: ['Mom says "Time for bath"', 'Child screams', 'Mom says "OK, 5 more minutes"', 'Child throws toy'], answer: 'Mom says "Time for bath"', explain: 'The antecedent is what happened right before the behavior.' },
      { scenario: 'Story: Mom says "Time for bath." Child screams and throws toy. Mom says "OK, 5 more minutes."', prompt: 'What is the Behavior?', options: ['Mom says "Time for bath"', 'Child screams and throws toy', 'Mom gives 5 more minutes', 'Child got mad'], answer: 'Child screams and throws toy', explain: 'Behavior must be observable. "Got mad" is an interpretation, not observable.' },
      { scenario: 'Story: Mom says "Time for bath." Child screams and throws toy. Mom says "OK, 5 more minutes."', prompt: 'What is the Consequence?', options: ['Child screams', 'Mom says "Time for bath"', 'Mom says "OK, 5 more minutes"', 'Child feels upset'], answer: 'Mom says "OK, 5 more minutes"', explain: 'The consequence is what changed right after the behavior.' },
      { scenario: 'Story: Teacher asks class to line up. Student drops to floor. Aide carries student to line.', prompt: 'What is the Antecedent?', options: ['Student drops to floor', 'Teacher asks class to line up', 'Aide carries student', 'Student doesn\'t want to'], answer: 'Teacher asks class to line up', explain: 'The direction to line up is the event right before the behavior.' },
      { scenario: 'Story: Teacher asks class to line up. Student drops to floor. Aide carries student to line.', prompt: 'What is the Behavior?', options: ['Teacher asks class to line up', 'Student drops to floor', 'Aide carries student to line', 'Student is defiant'], answer: 'Student drops to floor', explain: '"Drops to floor" is observable. "Is defiant" is a label, not a behavior.' },
      { scenario: 'Story: Sibling takes toy. Child hits sibling. Parent gives toy back to child.', prompt: 'What is the Antecedent?', options: ['Child hits sibling', 'Parent gives toy back', 'Sibling takes toy', 'Child is angry'], answer: 'Sibling takes toy', explain: 'The trigger event was the sibling taking the toy.' },
      { scenario: 'Story: Sibling takes toy. Child hits sibling. Parent gives toy back to child.', prompt: 'What is the Behavior?', options: ['Sibling takes toy', 'Child hits sibling', 'Parent gives toy back', 'Child got frustrated'], answer: 'Child hits sibling', explain: '"Hits sibling" is observable - you can see and count it.' },
      { scenario: 'Story: Sibling takes toy. Child hits sibling. Parent gives toy back to child.', prompt: 'What is the Consequence?', options: ['Sibling takes toy', 'Child hits sibling', 'Parent gives toy back to child', 'Everyone is upset'], answer: 'Parent gives toy back to child', explain: 'Hitting produced access to the toy - the consequence that followed.' },
      { scenario: 'Story: Dad says "Clean up." Child says "No!" and runs away. Dad cleans up himself.', prompt: 'What is the Consequence?', options: ['Dad says "Clean up"', 'Child says "No!" and runs', 'Dad cleans up himself', 'Child is lazy'], answer: 'Dad cleans up himself', explain: 'The task was removed - Dad doing it = escape from the demand for the child.' },
      { scenario: 'Story: Dad says "Clean up." Child says "No!" and runs away. Dad cleans up himself.', prompt: 'What is the Behavior?', options: ['Dad says "Clean up"', 'Child says "No!" and runs away', 'Dad cleans up himself', 'Child doesn\'t listen'], answer: 'Child says "No!" and runs away', explain: 'Observable actions: verbal refusal + running. "Doesn\'t listen" is a judgment.' },
    ],
  },
  {
    id: 'who_was_reinforced', title: 'Who Was Reinforced?', stage: 1, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['reinforcement', 'adult_loop'], est_seconds: 120,
    goal: 'Spot reinforcement loops for learner, coach, or both.',
    micro_tip: 'If you feel immediate relief, your brain learns too.',
    screens: { intro: { headline: 'Who Was Reinforced?', body: 'Learn to spot when behavior patterns reinforce the learner, the coach, or both.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child screams. Parent gives candy. Screaming stops. Parent feels relieved.', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Both', explain: 'Child got candy (access). Parent got relief (screaming stopped). Both brains learned.' },
      { scenario: 'Student raises hand. Teacher calls on them. Student answers correctly.', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Both', explain: 'Student got attention. Teacher got a correct answer (reinforcing calling on hand-raisers).' },
      { scenario: 'Child asks nicely. Parent says "Not right now." Child waits quietly.', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Neither', explain: 'The child\'s request was not reinforced (no access). Parent\'s boundary held - neutral.' },
      { scenario: 'Child tantrums. Parent removes homework. Parent feels instant relief.', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Both', explain: 'Child escaped homework. Parent escaped the tantrum. Both were reinforced.' },
      { scenario: 'Learner completes a task independently. Coach praises them.', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Learner', explain: 'Learner received praise (attention/acknowledgment) for task completion.' },
      { scenario: 'Child whines for 20 minutes. Parent holds boundary. Child eventually stops.', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Coach', explain: 'Parent\'s perseverance was reinforced - the boundary worked. Child\'s whining was NOT reinforced.' },
      { scenario: 'Teen argues. Parent yells back. Argument continues.', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Both', explain: 'Both get attention/engagement. The arguing loop reinforces both participants.' },
      { scenario: 'Child elopes. Aide chases and carries them back. Child giggles.', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Learner', explain: 'Child got attention + physical interaction (fun chase). Aide\'s behavior was not effective, so not reinforced.' },
      { scenario: 'Student completes work silently. Nobody notices.', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Neither', explain: 'The student\'s good behavior went unnoticed - no reinforcement was delivered.' },
      { scenario: 'Child hits sibling. Parent separates them. Hitting stops. Parent says "Finally, quiet."', options: ['Learner', 'Coach', 'Both', 'Neither'], answer: 'Both', explain: 'Child may have escaped sibling interaction. Parent got relief from the conflict.' },
    ],
  },
  {
    id: 'behavior_loop_puzzle', title: 'Behavior Loop Puzzle', stage: 1, difficulty: 'easy-med', difficulty_dots: 2,
    skill_tags: ['behavior_loop'], est_seconds: 90,
    goal: 'Arrange the loop: Trigger > Behavior > Consequence > Pattern.',
    micro_tip: 'Patterns don\'t mean "bad" - they mean "learned."',
    screens: { intro: { headline: 'Behavior Loop Puzzle', body: 'Practice turning chaos into a simple pattern loop.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Put these in order:', options: ['Child screams', 'Parent says "Time to go"', 'Parent says "5 more minutes"', 'Child learns: screaming delays leaving'], answer: 'Parent says "Time to go"', explain: 'Trigger > Behavior > Consequence > Pattern. The loop teaches the brain what works.', correct_order: ['Parent says "Time to go"', 'Child screams', 'Parent says "5 more minutes"', 'Child learns: screaming delays leaving'] },
      { scenario: 'Put these in order:', options: ['Student puts head down', 'Math worksheet presented', 'Teacher says "Take a break"', 'Student learns: shutting down removes work'], answer: 'Math worksheet presented', explain: 'The demand triggers the behavior, which produces escape, forming a pattern.', correct_order: ['Math worksheet presented', 'Student puts head down', 'Teacher says "Take a break"', 'Student learns: shutting down removes work'] },
      { scenario: 'Put these in order:', options: ['Parent says "What?!" and looks up', 'Parent on phone', 'Child yells "LOOK!"', 'Child learns: yelling gets attention'], answer: 'Parent on phone', explain: 'Reduced attention triggers attention-seeking, which produces the desired response.', correct_order: ['Parent on phone', 'Child yells "LOOK!"', 'Parent says "What?!" and looks up', 'Child learns: yelling gets attention'] },
      { scenario: 'Put these in order:', options: ['Child grabs toy from sibling', 'Child plays with toy', 'Sibling has desired toy', 'Child learns: grabbing gets things'], answer: 'Sibling has desired toy', explain: 'Seeing a preferred item triggers grabbing, which produces access.', correct_order: ['Sibling has desired toy', 'Child grabs toy from sibling', 'Child plays with toy', 'Child learns: grabbing gets things'] },
      { scenario: 'Put these in order:', options: ['Parent lies with child for 30 min', 'Bedtime announced', 'Child cries and clings', 'Child learns: crying extends parent time'], answer: 'Bedtime announced', explain: 'Bedtime trigger > clinging behavior > attention consequence > learned pattern.', correct_order: ['Bedtime announced', 'Child cries and clings', 'Parent lies with child for 30 min', 'Child learns: crying extends parent time'] },
      { scenario: 'Put these in order:', options: ['Student covers ears and hums', 'Noise is muffled', 'Loud cafeteria', 'Student learns: covering ears helps'], answer: 'Loud cafeteria', explain: 'Aversive sensory input triggers a coping behavior that reduces the input.', correct_order: ['Loud cafeteria', 'Student covers ears and hums', 'Noise is muffled', 'Student learns: covering ears helps'] },
    ],
  },
  {
    id: 'script_swap', title: 'Script Swap', stage: 1, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['scripts'], est_seconds: 120,
    goal: 'Convert reactive language into calm coaching scripts.',
    micro_tip: 'Short + calm + consistent beats long explanations in the moment.',
    screens: { intro: { headline: 'Script Swap', body: 'Practice what to say when things get tense.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Reactive: "Stop it right now or you\'re losing everything!"', prompt: 'Pick the best coaching script:', options: ['"I can see you\'re upset. Let\'s take a breath, then we\'ll figure it out."', '"You always do this! Why can\'t you just listen?"', '"If you don\'t stop, no screen time for a week."', '"Whatever, do what you want."'], answer: '"I can see you\'re upset. Let\'s take a breath, then we\'ll figure it out."', explain: 'Validates the emotion + gives a clear next step. Short, calm, structured.' },
      { scenario: 'Reactive: "Why are you acting like this?!"', prompt: 'Pick the best coaching script:', options: ['"This is hard. You can ask for help or take a break."', '"Because you never listen to me!"', '"Tell me what\'s wrong RIGHT NOW."', '"I don\'t even know what to do with you."'], answer: '"This is hard. You can ask for help or take a break."', explain: 'Acknowledges difficulty + offers two clear replacement options.' },
      { scenario: 'Reactive: "If you hit your brother one more time..."', prompt: 'Pick the best coaching script:', options: ['"Hands down. You can tell him with words or come to me."', '"That\'s it, you\'re grounded!"', '"How would YOU feel if someone hit YOU?"', '"I\'m so disappointed in you."'], answer: '"Hands down. You can tell him with words or come to me."', explain: 'Short direction + two replacement behaviors. No shaming.' },
      { scenario: 'Reactive: "We\'re never going to the store again!"', prompt: 'Pick the best coaching script:', options: ['"We\'re going to leave the store. Next time, we\'ll practice the plan first."', '"You ruined it for everyone as usual."', '"Fine, have the candy, just stop."', '"I can\'t take you anywhere!"'], answer: '"We\'re going to leave the store. Next time, we\'ll practice the plan first."', explain: 'States the consequence calmly + previews a proactive plan for next time.' },
      { scenario: 'Reactive: "You need to calm down!"', prompt: 'Pick the best coaching script:', options: ['"I\'m here. Let\'s breathe together. In... out..."', '"CALM DOWN RIGHT NOW!"', '"If you don\'t calm down, I\'m leaving."', '"You\'re overreacting."'], answer: '"I\'m here. Let\'s breathe together. In... out..."', explain: 'Co-regulation: presence + modeling the calm behavior you want to see.' },
      { scenario: 'Reactive: "I\'ve told you a thousand times!"', prompt: 'Pick the best coaching script:', options: ['"Let\'s try one more time. I\'ll show you first."', '"You never listen, do you?"', '"I give up."', '"Maybe if I yell louder you\'ll get it."'], answer: '"Let\'s try one more time. I\'ll show you first."', explain: 'Prompting + modeling instead of repeating a failed instruction.' },
      { scenario: 'Reactive: "You\'re being so bad today!"', prompt: 'Pick the best coaching script:', options: ['"You\'re having a hard time. Let\'s find something that helps."', '"Bad kids don\'t get treats."', '"What is WRONG with you today?"', '"Go to your room until you can be good."'], answer: '"You\'re having a hard time. Let\'s find something that helps."', explain: 'Labels the experience, not the child. Offers proactive support.' },
      { scenario: 'Reactive: "Fine, I\'ll just do it myself."', prompt: 'Pick the best coaching script:', options: ['"Let\'s do the first step together, then you try the next one."', '"You\'re too lazy to help."', '"Never mind, forget it."', '"You can\'t do anything right."'], answer: '"Let\'s do the first step together, then you try the next one."', explain: 'Scaffolding: break it down, do it together, then fade support.' },
      { scenario: 'Reactive: "You\'re going to sit here until it\'s done!"', prompt: 'Pick the best coaching script:', options: ['"Let\'s do 5 minutes, then you earn a 2-minute break."', '"No breaks until every single thing is finished."', '"I don\'t care how long it takes."', '"You\'re staying up all night if you have to."'], answer: '"Let\'s do 5 minutes, then you earn a 2-minute break."', explain: 'Structured work intervals + earned breaks. Manageable and motivating.' },
      { scenario: 'Reactive: "See? That\'s what happens when you don\'t listen."', prompt: 'Pick the best coaching script:', options: ['"That was hard. Next time, let\'s try a different approach."', '"I told you so!"', '"Maybe now you\'ll learn."', '"You brought this on yourself."'], answer: '"That was hard. Next time, let\'s try a different approach."', explain: 'Acknowledges the difficulty + forward-focused skill building.' },
    ],
  },

  // STAGE 2 - SKILL BUILDING
  {
    id: 'prompt_ladder', title: 'Prompt Ladder', stage: 2, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['prompting'], est_seconds: 120,
    goal: 'Order prompts least-to-most intrusive.',
    micro_tip: 'Start small. Prompting is about success, not control.',
    screens: { intro: { headline: 'Prompt Ladder', body: 'Practice how to give the right amount of help.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Order these prompts from LEAST to MOST intrusive:', options: ['Gesture (pointing)', 'Verbal hint', 'Model (show them)', 'Partial physical guidance', 'Full physical guidance'], answer: 'Gesture (pointing)', explain: 'Least-to-most: Gesture > Verbal > Model > Partial physical > Full physical.', correct_order: ['Gesture (pointing)', 'Verbal hint', 'Model (show them)', 'Partial physical guidance', 'Full physical guidance'] },
      { scenario: 'Least-to-most for teaching hand washing:', options: ['Point to sink', 'Say "Time to wash hands"', 'Wash your hands to show them', 'Guide their hands to faucet', 'Move their hands through the steps'], answer: 'Point to sink', explain: 'Always start with the least intrusive prompt that produces success.', correct_order: ['Point to sink', 'Say "Time to wash hands"', 'Wash your hands to show them', 'Guide their hands to faucet', 'Move their hands through the steps'] },
      { scenario: 'Least-to-most for shoe-tying:', options: ['Look at shoes meaningfully', '"What goes on your feet?"', 'Tie one shoe while they watch', 'Guide fingers to laces', 'Tie for them hand-over-hand'], answer: 'Look at shoes meaningfully', explain: 'Environmental cues > verbal > model > physical. Build independence by starting small.', correct_order: ['Look at shoes meaningfully', '"What goes on your feet?"', 'Tie one shoe while they watch', 'Guide fingers to laces', 'Tie for them hand-over-hand'] },
      { scenario: 'Least-to-most for cleaning up toys:', options: ['Gesture toward toy bin', '"Time to clean up"', 'Pick up a toy and put it away', 'Hand them a toy', 'Guide their hand to pick up and place'], answer: 'Gesture toward toy bin', explain: 'Visual prompt > verbal > model > partial physical > full physical.', correct_order: ['Gesture toward toy bin', '"Time to clean up"', 'Pick up a toy and put it away', 'Hand them a toy', 'Guide their hand to pick up and place'] },
      { scenario: 'Least-to-most for saying "please":', options: ['Pause and wait expectantly', '"What do we say?"', 'Model: "Can I have juice, please?"', 'Start the word: "Pl..."', 'Say it together: "Pleeeease"'], answer: 'Pause and wait expectantly', explain: 'A time delay (waiting) is one of the least intrusive prompts.', correct_order: ['Pause and wait expectantly', '"What do we say?"', 'Model: "Can I have juice, please?"', 'Start the word: "Pl..."', 'Say it together: "Pleeeease"'] },
    ],
  },
  {
    id: 'replacement_builder', title: 'Replacement Builder', stage: 2, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['replacement_skills'], est_seconds: 120,
    goal: 'Choose the best replacement skill for the function.',
    micro_tip: 'Replacement skills must pay off faster than problem behavior at first.',
    screens: { intro: { headline: 'Replacement Builder', body: 'Practice matching function to skill.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Function: ESCAPE. Child screams to avoid homework.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Ask for break', explain: 'Same function (escape), safer form. The break must be honored consistently at first.' },
      { scenario: 'Function: ATTENTION. Child hits to get parent to look.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Ask for attention', explain: 'Replace hitting with tapping, a "play with me" card, or saying "play with me."' },
      { scenario: 'Function: ACCESS. Child grabs snacks without asking.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Request item', explain: 'Teach "Can I have ___?" to get the same item through an appropriate request.' },
      { scenario: 'Function: SENSORY. Child bites themselves when overwhelmed.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Self-regulation strategy', explain: 'Provide a chewy, squeeze ball, or deep-pressure strategy that meets the sensory need safely.' },
      { scenario: 'Function: ESCAPE. Teen slams door to end argument.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Ask for break', explain: '"I need a minute" is a safer way to get space. Honor the break, then revisit.' },
      { scenario: 'Function: ATTENTION. Student calls out in class.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Ask for attention', explain: 'Raise hand, use a signal card. The replacement must produce attention just as reliably.' },
      { scenario: 'Function: ACCESS. Child tantrums for screen time.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Wait/tolerance', explain: 'When access can\'t always be immediate, teach waiting + use a visual timer or First-Then.' },
      { scenario: 'Function: ESCAPE. Child cries when task is hard.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Ask for help', explain: 'When escape is about difficulty (not just avoidance), asking for help keeps the task going with support.' },
      { scenario: 'Function: SENSORY. Student hums loudly during quiet work.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Self-regulation strategy', explain: 'Offer a fidget, noise-canceling headphones, or a quiet humming alternative.' },
      { scenario: 'Function: ATTENTION. Child fake-cries to get picked up.', options: ['Ask for break', 'Ask for help', 'Ask for attention', 'Request item', 'Wait/tolerance', 'Self-regulation strategy'], answer: 'Ask for attention', explain: 'Teach "Up please" or reaching with arms. A simpler behavior that gets the same result.' },
    ],
  },
  {
    id: 'replacement_match', title: 'Replacement Match', stage: 2, difficulty: 'easy-med', difficulty_dots: 2,
    skill_tags: ['replacement_skills'], est_seconds: 90,
    goal: 'Match replacement skills to function categories.',
    micro_tip: 'A replacement skill must meet the same need to stick.',
    screens: { intro: { headline: 'Replacement Match', body: 'Quick mapping: skill to function.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Tap a "play with me" card', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Attention', explain: 'This skill requests social interaction - matches attention function.' },
      { scenario: 'Ask for a break using a break card', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'Break requests serve the same function as escape - removing the demand briefly.' },
      { scenario: 'Point to desired item on a choice board', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Access', explain: 'Pointing to an item is a functional way to request access.' },
      { scenario: 'Use a fidget spinner during class', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'The fidget provides sensory input in a less disruptive way.' },
      { scenario: 'Say "Can I have a turn?"', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Access', explain: 'Requesting a turn is a functional replacement for grabbing.' },
      { scenario: 'Raise hand and wait', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Attention', explain: 'Hand-raising is an appropriate way to get teacher attention.' },
      { scenario: 'Squeeze a stress ball when frustrated', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Sensory/Body need', explain: 'The stress ball provides physical input for regulation.' },
      { scenario: 'Say "This is hard, can you help me?"', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'Asking for help reduces task difficulty - a form of modified escape.' },
    ],
  },
  {
    id: 'first_then_creator', title: 'First-Then Creator', stage: 2, difficulty: 'easy', difficulty_dots: 1,
    skill_tags: ['reinforcement_planning'], est_seconds: 90,
    goal: 'Build a realistic First-Then plan.',
    micro_tip: 'If "Then" is not motivating, First-Then will not work.',
    screens: { intro: { headline: 'First-Then Creator', body: 'Practice making First-Then plans that actually get used.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child needs to brush teeth but hates it. Best First-Then?', options: ['First: brush teeth (2 min). Then: pick a bedtime story.', 'First: brush teeth. Then: maybe a treat sometime.', 'First: brush teeth perfectly. Then: free time tomorrow.', 'First: watch TV. Then: brush teeth.'], answer: 'First: brush teeth (2 min). Then: pick a bedtime story.', explain: 'First is short and clear. Then is immediate and motivating.' },
      { scenario: 'Student avoids writing. What works?', options: ['First: write 3 sentences. Then: 5 min drawing time.', 'First: finish entire essay. Then: recess on Friday.', 'First: sit quietly. Then: nothing specific.', 'First: drawing. Then: writing.'], answer: 'First: write 3 sentences. Then: 5 min drawing time.', explain: 'Small, achievable First + immediate, preferred Then = success.' },
      { scenario: 'Child refuses to get dressed in the morning.', options: ['First: get dressed. Then: pick breakfast cereal.', 'First: get dressed perfectly. Then: maybe park later.', 'First: eat breakfast. Then: get dressed.', 'First: get dressed. Then: you should feel proud.'], answer: 'First: get dressed. Then: pick breakfast cereal.', explain: 'Choice of cereal is immediate and motivating. The Then happens right away.' },
      { scenario: 'Learner struggles with clean-up time.', options: ['First: put 5 toys away. Then: pick next activity.', 'First: clean entire room. Then: free time in an hour.', 'First: clean up. Then: avoid punishment.', 'First: play. Then: clean up.'], answer: 'First: put 5 toys away. Then: pick next activity.', explain: 'Small task (5 toys) + immediate reinforcer (choice of next activity).' },
      { scenario: 'Teen needs to do homework but keeps avoiding it.', options: ['First: 15 min homework. Then: 10 min phone break.', 'First: all homework. Then: weekend plans.', 'First: homework. Then: I will not be disappointed.', 'First: phone time. Then: homework.'], answer: 'First: 15 min homework. Then: 10 min phone break.', explain: 'Timed chunk (not "all") + high-preference Then (phone) + immediate.' },
      { scenario: 'Child needs to wait at the doctor\'s office.', options: ['First: wait quietly for 5 min. Then: play a game on the tablet.', 'First: be good all day. Then: dessert tonight.', 'First: wait. Then: nothing.', 'First: play tablet. Then: wait.'], answer: 'First: wait quietly for 5 min. Then: play a game on the tablet.', explain: 'Clear time limit + high-preference activity immediately after.' },
      { scenario: 'Learner needs to practice tying shoes.', options: ['First: try 3 shoe ties. Then: pick a song to listen to.', 'First: tie shoes perfectly 10 times. Then: maybe a prize later.', 'First: tie shoes. Then: we will stop nagging.', 'First: watch a video. Then: tie shoes.'], answer: 'First: try 3 shoe ties. Then: pick a song to listen to.', explain: '"Try" reduces pressure. 3 is doable. Song choice is immediate and fun.' },
      { scenario: 'Child needs to transition from playground to car.', options: ['First: walk to car. Then: pick the music for the drive.', 'First: leave immediately. Then: we will come back someday.', 'First: stop having fun. Then: go home.', 'First: get in car. Then: you should be grateful we came.'], answer: 'First: walk to car. Then: pick the music for the drive.', explain: 'Clear action + immediate, child-chosen reinforcer during the transition.' },
    ],
  },
  {
    id: 'visual_timer_planner', title: 'Visual Timer Planner', stage: 2, difficulty: 'easy-med', difficulty_dots: 2,
    skill_tags: ['supports'], est_seconds: 90,
    goal: 'Choose the best support tool for the situation.',
    micro_tip: 'Visuals reduce arguing - because the visual becomes the "bad guy," not you.',
    screens: { intro: { headline: 'Visual Timer Planner', body: 'Practice picking the right support for the moment.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child has meltdowns during transitions between activities.', options: ['Visual timer', 'Visual schedule', 'Token board', 'First-Then', 'Choice board'], answer: 'Visual timer', explain: 'A countdown timer makes the transition predictable and removes surprise.' },
      { scenario: 'Morning routine is chaotic - child never knows what comes next.', options: ['Visual timer', 'Visual schedule', 'Token board', 'First-Then', 'Choice board'], answer: 'Visual schedule', explain: 'A sequence of steps reduces the need for repeated verbal prompts.' },
      { scenario: 'Child needs motivation to complete 4 small tasks.', options: ['Visual timer', 'Visual schedule', 'Token board', 'First-Then', 'Choice board'], answer: 'Token board', explain: 'Tokens for each completed task build toward a reinforcer.' },
      { scenario: 'Child refuses non-preferred activity but loves one specific activity.', options: ['Visual timer', 'Visual schedule', 'Token board', 'First-Then', 'Choice board'], answer: 'First-Then', explain: 'First (non-preferred) then (preferred) makes the deal visible and concrete.' },
      { scenario: 'Child gets upset because they "never get to choose."', options: ['Visual timer', 'Visual schedule', 'Token board', 'First-Then', 'Choice board'], answer: 'Choice board', explain: 'A choice board provides controlled options - meeting the access/control need.' },
      { scenario: 'Learner has trouble waiting for a turn.', options: ['Visual timer', 'Visual schedule', 'Token board', 'First-Then', 'Choice board'], answer: 'Visual timer', explain: 'The timer shows "how long until my turn" - makes waiting concrete.' },
      { scenario: 'Child does well with routine but struggles when the order changes.', options: ['Visual timer', 'Visual schedule', 'Token board', 'First-Then', 'Choice board'], answer: 'Visual schedule', explain: 'A schedule they can reference reduces anxiety about what is next.' },
      { scenario: 'Multiple children argue about which activity to do during free time.', options: ['Visual timer', 'Visual schedule', 'Token board', 'First-Then', 'Choice board'], answer: 'Choice board', explain: 'A choice board gives everyone clear, finite options to pick from.' },
    ],
  },
  {
    id: 'data_detective', title: 'Data Detective', stage: 2, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['data'], est_seconds: 120,
    goal: 'Interpret simple behavior trends.',
    micro_tip: 'Small data beats no data. Patterns show up over weeks.',
    screens: { intro: { headline: 'Data Detective', body: 'Practice reading simple behavior trends.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Tantrums per day this week: Mon 5, Tue 4, Wed 3, Thu 2, Fri 2. What happened?', options: ['Increased', 'Decreased', 'Stayed about the same', 'More intense', 'Less intense'], answer: 'Decreased', explain: 'The count went from 5 to 2. Clear downward trend.' },
      { scenario: 'Hitting incidents: Mon 2, Tue 2, Wed 3, Thu 2, Fri 2. What happened?', options: ['Increased', 'Decreased', 'Stayed about the same', 'More intense', 'Less intense'], answer: 'Stayed about the same', explain: 'The count hovers around 2, with one small spike. No clear trend.' },
      { scenario: 'Meltdown minutes: Mon 5, Tue 8, Wed 12, Thu 15, Fri 20. What happened?', options: ['Increased', 'Decreased', 'Stayed about the same', 'More intense', 'Less intense'], answer: 'More intense', explain: 'Duration of each episode is growing.' },
      { scenario: 'Elopements: Mon 3, Tue 4, Wed 5, Thu 6, Fri 7. What happened?', options: ['Increased', 'Decreased', 'Stayed about the same', 'More intense', 'Less intense'], answer: 'Increased', explain: 'Steady climb from 3 to 7. Consistent upward trend.' },
      { scenario: 'Crying (new plan started Wed): Mon 5, Tue 6, Wed 7, Thu 4, Fri 2.', options: ['Increased', 'Decreased', 'Stayed about the same', 'More intense', 'Less intense'], answer: 'Decreased', explain: 'There was an initial spike (extinction burst), then a decrease. Plan may be working.' },
      { scenario: 'Compliance: Mon 3/10, Tue 4/10, Wed 5/10, Thu 6/10, Fri 7/10.', options: ['Increased', 'Decreased', 'Stayed about the same', 'More intense', 'Less intense'], answer: 'Increased', explain: 'Compliance rate improved from 30% to 70% over the week.' },
      { scenario: 'Hand-raising: Mon 0, Tue 1, Wed 1, Thu 1, Fri 2.', options: ['Increased', 'Decreased', 'Stayed about the same', 'More intense', 'Less intense'], answer: 'Increased', explain: 'Small but steady increase from 0 to 2. Progress!' },
      { scenario: 'Aggression intensity (1-5): Mon 4, Tue 4, Wed 3, Thu 2, Fri 2.', options: ['Increased', 'Decreased', 'Stayed about the same', 'More intense', 'Less intense'], answer: 'Less intense', explain: 'Intensity dropped from 4 to 2. Severity decreased.' },
    ],
  },
  {
    id: 'frequency_vs_duration', title: 'Frequency vs Duration', stage: 2, difficulty: 'easy', difficulty_dots: 1,
    skill_tags: ['measurement'], est_seconds: 90,
    goal: 'Choose the best measurement: frequency, duration, or latency.',
    micro_tip: 'Quick and repeatable = frequency. Lasts a while = duration. About starting = latency.',
    screens: { intro: { headline: 'Frequency vs Duration', body: 'Choose the simplest data type for the behavior.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child hits sibling multiple times per day.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Frequency', explain: 'Each hit is a quick, countable event.' },
      { scenario: 'Child has tantrums that last 10-45 minutes.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Duration', explain: 'The length of each tantrum matters more than just counting them.' },
      { scenario: 'Child takes 15 minutes to start homework after being told.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Latency', explain: 'Latency = time from the direction to starting the task.' },
      { scenario: 'Student calls out 8 times during a 30-minute lesson.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Frequency', explain: 'Calling out is a discrete, countable behavior.' },
      { scenario: 'Meltdowns that last varying amounts of time.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Duration', explain: 'When the behavior extends over time, duration captures the full picture.' },
      { scenario: 'Child throws food at every meal.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Frequency', explain: 'Each throw is a discrete event - count how many per meal.' },
      { scenario: 'Teen takes 30 minutes to get out of bed after alarm.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Latency', explain: 'Time between alarm (cue) and action (getting up) = latency.' },
      { scenario: 'Child whines for extended periods throughout the day.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Duration', explain: 'Whining is continuous - track how many minutes per occurrence.' },
      { scenario: 'Student raises hand 12 times during class.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Frequency', explain: 'Discrete, countable events. Simple tally.' },
      { scenario: 'Child takes 5 minutes to respond when name is called.', options: ['Frequency', 'Duration', 'Latency'], answer: 'Latency', explain: 'Time from the prompt (name call) to the response = latency.' },
    ],
  },
  {
    id: 'intensity_rating_trainer', title: 'Intensity Rating Trainer', stage: 2, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['intensity'], est_seconds: 120,
    goal: 'Practice consistent intensity ratings using anchors.',
    micro_tip: 'Anchors keep ratings consistent across days and people.',
    screens: { intro: { headline: 'Intensity Rating Trainer', body: 'Practice using anchor examples for 1-5 intensity.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child whimpers quietly and puts head down. Anchor: 1=silent refusal, 3=loud crying, 5=property destruction + aggression.', options: ['1', '2', '3', '4', '5'], answer: '2', explain: 'Whimpering is above silent refusal but below loud crying.' },
      { scenario: 'Child screams, throws chair, kicks wall.', options: ['1', '2', '3', '4', '5'], answer: '5', explain: 'Throwing furniture + kicking = property destruction territory.' },
      { scenario: 'Child says "I don\'t want to" in a calm voice.', options: ['1', '2', '3', '4', '5'], answer: '1', explain: 'Calm verbal refusal is the lowest intensity anchor.' },
      { scenario: 'Child yells "NO!" and stamps foot.', options: ['1', '2', '3', '4', '5'], answer: '3', explain: 'Yelling with foot-stamping matches the midpoint anchor.' },
      { scenario: 'Child cries loudly and drops to floor but does not hit.', options: ['1', '2', '3', '4', '5'], answer: '4', explain: 'Loud crying + dropping to floor is above 3 but below 5 (no aggression).' },
      { scenario: 'Child pushes materials off desk quietly.', options: ['1', '2', '3', '4', '5'], answer: '3', explain: 'Pushing materials off is disruption without major aggression.' },
      { scenario: 'Learner tenses body and clenches fists but does not act.', options: ['1', '2', '3', '4', '5'], answer: '2', explain: 'Visible tension without verbal or physical outburst.' },
      { scenario: 'Child sobs softly with tears.', options: ['1', '2', '3', '4', '5'], answer: '2', explain: 'Soft sobbing is above teary-eyed but below loud crying.' },
      { scenario: 'Teen yells profanity and slams door.', options: ['1', '2', '3', '4', '5'], answer: '4', explain: 'Yelling profanity + slamming is above raised voice but the door is not destroyed.' },
      { scenario: 'Child sits rigidly, will not move or speak for 5+ minutes.', options: ['1', '2', '3', '4', '5'], answer: '3', explain: 'Rigid shutdown matches the 5+ minute middle anchor.' },
    ],
  },
  {
    id: 'myth_buster', title: 'Myth Buster', stage: 2, difficulty: 'easy', difficulty_dots: 1,
    skill_tags: ['fundamentals'], est_seconds: 90,
    goal: 'Correct common misconceptions.',
    micro_tip: 'Clarity reduces guilt. Guilt reduces follow-through.',
    screens: { intro: { headline: 'Myth Buster', body: 'Practice the most important mental flips in behavior science.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: '"Ignoring bad behavior always makes it go away."', options: ['True', 'False'], answer: 'False', explain: 'Ignoring only works if the function is attention. For escape or access, ignoring may not help.' },
      { scenario: '"Reinforcement only means giving rewards."', options: ['True', 'False'], answer: 'False', explain: 'Reinforcement = anything that increases behavior. Removing a demand (negative reinforcement) counts too.' },
      { scenario: '"If a child knows better, they should do better."', options: ['True', 'False'], answer: 'False', explain: 'Knowing and doing are different skills. Behavior is influenced by environment and reinforcement.' },
      { scenario: '"Punishment stops behavior permanently."', options: ['True', 'False'], answer: 'False', explain: 'Punishment may suppress behavior temporarily but does not teach replacement skills.' },
      { scenario: '"All behavior is communication."', options: ['True', 'False'], answer: 'True', explain: 'Even challenging behavior serves a function - it is how the brain has learned to get needs met.' },
      { scenario: '"Giving in occasionally is just as bad as giving in every time."', options: ['True', 'False'], answer: 'False', explain: 'Intermittent reinforcement actually makes behavior STRONGER and harder to change.' },
      { scenario: '"Children choose to misbehave."', options: ['True', 'False'], answer: 'False', explain: 'Behavior is learned through reinforcement history, not moral choice.' },
      { scenario: '"Consistency means being rigid and never flexible."', options: ['True', 'False'], answer: 'False', explain: 'Consistency means predictable responses, not rigidity.' },
      { scenario: '"If a consequence works (stops behavior), it is always the right choice."', options: ['True', 'False'], answer: 'False', explain: 'Stopping behavior short-term does not mean building skills long-term.' },
      { scenario: '"Positive reinforcement means you are being permissive."', options: ['True', 'False'], answer: 'False', explain: 'Positive reinforcement strengthens desired behavior - it is proactive teaching, not permissiveness.' },
      { scenario: '"Extinction bursts are a sign the plan is not working."', options: ['True', 'False'], answer: 'False', explain: 'Extinction bursts (temporary increase) are a sign the plan IS working.' },
      { scenario: '"Sensory-seeking behavior is always a problem to fix."', options: ['True', 'False'], answer: 'False', explain: 'Sensory needs are valid. The goal is safer, more appropriate ways to meet them.' },
    ],
  },
  {
    id: 'calm_or_escalate', title: 'Calm or Escalate?', stage: 2, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['de_escalation'], est_seconds: 120,
    goal: 'Choose the best immediate response to reduce escalation.',
    micro_tip: 'In escalation: fewer words + more structure.',
    screens: { intro: { headline: 'Calm or Escalate?', body: 'Practice what helps in the moment - not what sounds good later.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child is yelling and throwing pillows. Escalating.', options: ['Stand close, speak quietly: "I\'m here. Pillows stay on the couch."', 'Yell "Stop throwing things RIGHT NOW!"', 'Ask "Why are you doing this?!"', 'Leave the room without a word'], answer: 'Stand close, speak quietly: "I\'m here. Pillows stay on the couch."', explain: 'Proximity + low volume + simple direction reduces intensity.' },
      { scenario: 'Teen is slamming doors and cursing.', options: ['Wait 30 seconds. Calmly: "I\'ll be in the kitchen when you\'re ready."', '"You\'re grounded for a month!"', '"Come here and explain yourself!"', '"If you break that door, you\'re paying for it!"'], answer: 'Wait 30 seconds. Calmly: "I\'ll be in the kitchen when you\'re ready."', explain: 'Give space + offer reconnection without a demand.' },
      { scenario: 'Student is crying at their desk and refusing to work.', options: ['Sit nearby quietly, then: "Take your time. I\'m here when you\'re ready."', '"If you don\'t start, you\'ll miss recess."', '"Everyone else is doing their work."', '"Stop crying and get back to work."'], answer: 'Sit nearby quietly, then: "Take your time. I\'m here when you\'re ready."', explain: 'Presence without pressure. The student needs regulation before compliance.' },
      { scenario: 'Child is hitting themselves during a meltdown.', options: ['Stay close. Offer a pillow: "You can squeeze this."', '"Stop that! You\'re hurting yourself!"', 'Grab their hands to stop them', 'Walk away to "not reinforce it"'], answer: 'Stay close. Offer a pillow: "You can squeeze this."', explain: 'Redirect the physical energy to something safer. Safety + calm presence.' },
      { scenario: 'Two children are arguing over a toy. Both getting louder.', options: ['"I\'ll hold the toy for 10 seconds while you both take a breath."', '"If you can\'t share, nobody gets it!"', '"Who had it first?"', '"You\'re both being ridiculous."'], answer: '"I\'ll hold the toy for 10 seconds while you both take a breath."', explain: 'Neutral hold + brief pause reduces urgency and competition.' },
      { scenario: 'Child says "I hate you!" during a conflict.', options: ['"You\'re upset. That\'s OK. We\'ll talk when things are calmer."', '"How dare you say that to me!"', '"Fine, then I won\'t help you."', '"Say sorry right now."'], answer: '"You\'re upset. That\'s OK. We\'ll talk when things are calmer."', explain: 'Label emotion + do not take it personally + defer the conversation.' },
      { scenario: 'Learner bolts out of the classroom.', options: ['Follow at safe distance. Calmly: "I see you. I\'m here when you\'re ready."', 'Chase and grab them', '"If you run, you lose recess for a week!"', 'Ignore it completely'], answer: 'Follow at safe distance. Calmly: "I see you. I\'m here when you\'re ready."', explain: 'Safety (following) + low demands + availability = de-escalation.' },
      { scenario: 'Child starts breathing fast and looks panicked.', options: ['"Let\'s breathe together. In... 2... 3... out... 2... 3..."', '"Calm down, there\'s nothing to be scared of."', '"What\'s wrong now?"', '"You\'re fine, stop overreacting."'], answer: '"Let\'s breathe together. In... 2... 3... out... 2... 3..."', explain: 'Co-regulation: model the breathing. Do not dismiss the feeling.' },
      { scenario: 'Child is whining and escalating during homework.', options: ['"Let\'s do just this one problem together, then take a break."', '"You\'re not getting up until it\'s all done."', '"Stop whining!"', '"Forget it, I\'ll tell your teacher you didn\'t do it."'], answer: '"Let\'s do just this one problem together, then take a break."', explain: 'Reduce the demand + offer support + break = manageable.' },
      { scenario: 'Two siblings are physically fighting.', options: ['Separate calmly: "Bodies apart. Couch and chair. We talk in 2 minutes."', '"Who started it?!"', '"Both of you, go to your rooms!"', 'Start lecturing about respect'], answer: 'Separate calmly: "Bodies apart. Couch and chair. We talk in 2 minutes."', explain: 'Safety first (separate). Clear, brief directions. Process later.' },
    ],
  },
  {
    id: 'ten_second_reset', title: '10-Second Reset', stage: 2, difficulty: 'easy', difficulty_dots: 1,
    skill_tags: ['coach_regulation'], est_seconds: 60,
    goal: 'Practice a quick regulation reset as a coach.',
    micro_tip: 'Your nervous system sets the temperature of the room.',
    screens: { intro: { headline: '10-Second Reset', body: 'A quick reset helps you respond instead of react.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Take a deep breath in for 4 counts... hold for 2... breathe out for 4 counts. Press "Done" when complete.', options: ['Done'], answer: 'Done', explain: 'You just gave your nervous system a reset. That 10 seconds changes your next response.' },
    ],
  },
  {
    id: 'trigger_spotter', title: 'Trigger Spotter', stage: 2, difficulty: 'easy-med', difficulty_dots: 2,
    skill_tags: ['antecedents'], est_seconds: 90,
    goal: 'Identify the trigger/antecedent in a story.',
    micro_tip: 'Triggers are often small: transitions, denied access, attention shifts, or hard tasks.',
    screens: { intro: { headline: 'Trigger Spotter', body: 'Practice finding what set the behavior off.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child was playing happily. Mom said "Time to go." Child screamed.', options: ['Playing happily', 'Mom said "Time to go"', 'Child screamed', 'Child was at the park'], answer: 'Mom said "Time to go"', explain: 'The transition direction happened immediately before the behavior.' },
      { scenario: 'Student was working quietly. Teacher handed out a harder worksheet. Student tore it up.', options: ['Working quietly', 'Teacher handed out harder worksheet', 'Student tore it up', 'It was afternoon'], answer: 'Teacher handed out harder worksheet', explain: 'The new, harder demand triggered the behavior.' },
      { scenario: 'Siblings were sharing a toy. One sibling took the toy away. Other sibling hit them.', options: ['Sharing a toy', 'Sibling took toy away', 'Other sibling hit them', 'They were in the playroom'], answer: 'Sibling took toy away', explain: 'Loss of access (toy removed) triggered the hitting.' },
      { scenario: 'Parent was talking to neighbor. Child pulled on parent\'s arm and cried.', options: ['Parent talking to neighbor', 'Child pulled arm', 'Child cried', 'They were outside'], answer: 'Parent talking to neighbor', explain: 'Parent attention shifted away from child.' },
      { scenario: 'It was time for bed. Child started a tantrum when lights were turned off.', options: ['It was bedtime', 'Lights turned off', 'Child started tantrum', 'It was dark'], answer: 'Lights turned off', explain: 'The specific event (lights off) immediately preceded the behavior.' },
      { scenario: 'Teacher asked class to put away iPads. One student threw iPad.', options: ['Teacher asked to put away iPads', 'Student threw iPad', 'Class was using iPads', 'It was transition time'], answer: 'Teacher asked to put away iPads', explain: 'The direction to remove a preferred item triggered the behavior.' },
      { scenario: 'Child saw their favorite snack on the counter. They climbed up to get it.', options: ['Snack was on counter', 'Child climbed up', 'Child was hungry', 'It was snack time'], answer: 'Snack was on counter', explain: 'The visual presence of the preferred item triggered the behavior.' },
      { scenario: 'Dad said "No more YouTube." Child threw remote.', options: ['YouTube was on', 'Dad said "No more YouTube"', 'Child threw remote', 'It was evening'], answer: 'Dad said "No more YouTube"', explain: 'The denial of access (ending YouTube) triggered the behavior.' },
      { scenario: 'Fire alarm went off. Student covered ears and ran out of room.', options: ['Fire alarm went off', 'Student covered ears', 'Student ran out', 'It was during class'], answer: 'Fire alarm went off', explain: 'The sudden, aversive sensory input (alarm) triggered the response.' },
      { scenario: 'Child was asked to share their new toy with a visiting cousin. Child screamed "NO!"', options: ['Cousin was visiting', 'Asked to share new toy', 'Child screamed', 'Child had a new toy'], answer: 'Asked to share new toy', explain: 'The demand to share (potential loss of access) triggered the refusal.' },
    ],
  },
  {
    id: 'consequence_spotter', title: 'Consequence Spotter', stage: 2, difficulty: 'easy-med', difficulty_dots: 2,
    skill_tags: ['consequences'], est_seconds: 90,
    goal: 'Identify what changed after the behavior.',
    micro_tip: 'Consequence = what changed right after (including what ended).',
    screens: { intro: { headline: 'Consequence Spotter', body: 'Practice seeing what the behavior produced.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child hit sibling. Parent yelled, hugged the sibling, and sent child to room.', prompt: 'What consequences did the behavior produce?', options: ['Parent attention (yelling)', 'Sent to room (escape)', 'Both of these', 'None of these'], answer: 'Both of these', explain: 'Hitting produced attention AND escape from the situation.' },
      { scenario: 'Student called out. Teacher said "Raise your hand" and continued.', prompt: 'What was the consequence?', options: ['Brief teacher attention', 'Lost recess', 'Nothing changed', 'Got to answer'], answer: 'Brief teacher attention', explain: 'Even a brief correction is a form of attention.' },
      { scenario: 'Child refused dinner. Parent made them a sandwich instead.', prompt: 'What was the consequence?', options: ['Got preferred food (access)', 'Went hungry', 'Got attention', 'Was punished'], answer: 'Got preferred food (access)', explain: 'Refusal produced a preferred alternative.' },
      { scenario: 'Teen argued about homework. Parent said "Just go to bed."', prompt: 'What was the consequence?', options: ['Homework removed (escape)', 'Got in trouble', 'Nothing changed', 'Got extra homework'], answer: 'Homework removed (escape)', explain: 'The argument successfully removed the homework demand.' },
      { scenario: 'Child completed morning routine independently. Parent said "Great job!" with high-five.', prompt: 'What was the consequence?', options: ['Praise + attention', 'Nothing special', 'Access to activity', 'Escape from routine'], answer: 'Praise + attention', explain: 'Verbal praise and physical interaction reinforce the independent routine.' },
      { scenario: 'Student eloped. Aide followed and walked them around the hall for 5 minutes.', prompt: 'What was the consequence?', options: ['1-on-1 attention + escape from class', 'Punishment', 'Nothing changed', 'Lost recess'], answer: '1-on-1 attention + escape from class', explain: 'Elopement produced both adult attention and removal from class demands.' },
      { scenario: 'Child threw food. Parent silently cleaned it up without looking at child.', prompt: 'What was the consequence?', options: ['Minimal attention delivered', 'Access to more food', 'Escape from eating', 'Nothing happened'], answer: 'Minimal attention delivered', explain: 'Cleaning up is still a response to the behavior, even if attention was minimized.' },
      { scenario: 'Child cried at bedtime. Parent returned 3 times to check on them.', prompt: 'What was the consequence?', options: ['Extended parent attention', 'Escape from bed', 'Access to toy', 'Nothing'], answer: 'Extended parent attention', explain: 'Each return delivered parent presence/attention, reinforcing the crying.' },
      { scenario: 'Student completed 5 math problems. Teacher let them choose a game for 5 min.', prompt: 'What was the consequence?', options: ['Access to preferred activity', 'Attention', 'Escape from more math', 'Both access and escape'], answer: 'Both access and escape', explain: 'The student got a preferred activity (access) AND a break from math (escape).' },
      { scenario: 'Child bit their arm. Parent rushed over and held them tightly.', prompt: 'What was the consequence?', options: ['Attention + sensory input (deep pressure)', 'Punishment', 'Escape', 'Nothing'], answer: 'Attention + sensory input (deep pressure)', explain: 'Rushing over = attention. Tight hold = deep pressure (sensory). Both delivered simultaneously.' },
    ],
  },
  {
    id: 'what_would_nova_say', title: 'What Would Nova Say?', stage: 2, difficulty: 'easy-med', difficulty_dots: 2,
    skill_tags: ['tone', 'coaching'], est_seconds: 90,
    goal: 'Pick the most supportive, effective coaching response.',
    micro_tip: 'Support + structure = follow-through.',
    screens: { intro: { headline: 'What Would Nova Say?', body: 'Practice the tone that reduces shame and increases action.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Parent says: "I gave in again. I\'m a terrible parent."', options: ['"Giving in is human. Let\'s figure out one small change for next time."', '"You really should not have done that."', '"Everyone messes up, don\'t worry."', '"Just be stronger next time."'], answer: '"Giving in is human. Let\'s figure out one small change for next time."', explain: 'Validates + normalizes + gives a concrete, small next step.' },
      { scenario: 'Parent says: "Nothing is working. I want to give up."', options: ['"That\'s exhausting. Let\'s look at the data - sometimes patterns hide progress."', '"It\'ll get better eventually."', '"You just need to be more consistent."', '"Maybe this approach is not for your family."'], answer: '"That\'s exhausting. Let\'s look at the data - sometimes patterns hide progress."', explain: 'Validates the feeling + offers data-driven hope + partnership.' },
      { scenario: 'Parent says: "My child hit me today. I yelled back."', options: ['"That sounds really hard. Your safety matters too. Let\'s plan for next time."', '"You should not yell at your child."', '"It\'s fine, all parents yell."', '"Your child needs more consequences."'], answer: '"That sounds really hard. Your safety matters too. Let\'s plan for next time."', explain: 'Acknowledges difficulty + affirms parent safety + forward-focused.' },
      { scenario: 'Parent says: "I don\'t understand why they keep doing this."', options: ['"Behavior always has a reason - let\'s look at what happens before and after."', '"Because they are not trying hard enough."', '"Some kids are just difficult."', '"You\'ll figure it out eventually."'], answer: '"Behavior always has a reason - let\'s look at what happens before and after."', explain: 'Teaches the ABC framework gently while normalizing the confusion.' },
      { scenario: 'Parent says: "Everyone judges me when my kid melts down in public."', options: ['"That is one of the hardest parts. Your child\'s progress is not measured by strangers."', '"Just ignore what people think."', '"Maybe avoid public places for now."', '"Try controlling the behavior before going out."'], answer: '"That is one of the hardest parts. Your child\'s progress is not measured by strangers."', explain: 'Validates the social pain + reframes success as personal, not performative.' },
      { scenario: 'Parent made progress - child had 3 good days in a row.', options: ['"Three days! Your consistency is paying off. What do you think helped?"', '"Great, keep it up."', '"Don\'t get too excited, it might not last."', '"That\'s just luck."'], answer: '"Three days! Your consistency is paying off. What do you think helped?"', explain: 'Celebrates specifically + attributes success to the parent + invites reflection.' },
      { scenario: 'Parent: "I tried the plan but my partner does not do it the same way."', options: ['"That\'s common. Let\'s find the 1-2 things you both can be consistent on first."', '"Both of you need to be 100% on the same page."', '"That\'s why it is not working."', '"Just do it your way and ignore them."'], answer: '"That\'s common. Let\'s find the 1-2 things you both can be consistent on first."', explain: 'Normalizes + reduces overwhelm + focuses on achievable consistency.' },
      { scenario: 'Parent: "I did everything right and it still didn\'t work today."', options: ['"Sometimes it takes repetition. One bad day does not undo progress."', '"You must have missed something."', '"Just keep trying harder."', '"That\'s life."'], answer: '"Sometimes it takes repetition. One bad day does not undo progress."', explain: 'Reframes as normal learning + protects against discouragement.' },
      { scenario: 'Parent: "Should I be collecting data? It feels weird."', options: ['"Even simple notes help you see patterns. Let\'s start with just tally marks."', '"Yes, you need to track everything."', '"Data is not that important for parents."', '"Just trust your instincts."'], answer: '"Even simple notes help you see patterns. Let\'s start with just tally marks."', explain: 'Normalizes data collection + starts small + shows the benefit.' },
      { scenario: 'Parent: "I read that ABA is harmful. Should I be worried?"', options: ['"There are many approaches under that umbrella. Let\'s focus on what feels right for YOUR family."', '"ABA is the gold standard, ignore the critics."', '"Yeah, it can be harmful."', '"Don\'t read things online."'], answer: '"There are many approaches under that umbrella. Let\'s focus on what feels right for YOUR family."', explain: 'Acknowledges the concern without dismissing + empowers parent decision-making.' },
    ],
  },

  // STAGE 3 - ADVANCED
  {
    id: 'micro_scenario_drills', title: 'Micro Scenario Drills (30s)', stage: 3, difficulty: 'hard', difficulty_dots: 4,
    skill_tags: ['mixed'], est_seconds: 60,
    goal: 'Build fast fluency under time pressure.',
    micro_tip: 'Fast does not mean perfect - fast means practiced.',
    screens: { intro: { headline: 'Micro Scenario Drills', body: '30 seconds. Quick decisions. Calm learning.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child screams when iPad is taken. Function?', options: ['Access', 'Escape/Avoid', 'Attention', 'Sensory/Body need'], answer: 'Access', explain: 'Behavior followed removal of preferred item.' },
      { scenario: 'Student puts head down when test starts. Function?', options: ['Escape/Avoid', 'Access', 'Attention', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'Behavior followed a demand.' },
      { scenario: 'Child yells "Mom!" until parent responds. Function?', options: ['Attention', 'Escape/Avoid', 'Access', 'Sensory/Body need'], answer: 'Attention', explain: 'Behavior stops when parent responds.' },
      { scenario: 'Child hums and flaps hands alone. Function?', options: ['Sensory/Body need', 'Attention', 'Access', 'Escape/Avoid'], answer: 'Sensory/Body need', explain: 'Happens without social consequence.' },
      { scenario: 'Teen refuses to clean room, goes to play video games. Function?', options: ['Escape/Avoid', 'Access', 'Attention', 'Sensory/Body need'], answer: 'Escape/Avoid', explain: 'The refusal removes the cleaning demand.' },
      { scenario: 'Child brings parent book after book. Function?', options: ['Attention', 'Access', 'Escape/Avoid', 'Sensory/Body need'], answer: 'Attention', explain: 'Each book produces shared reading time.' },
    ],
  },
  {
    id: 'streak_challenge', title: 'Streak Challenge', stage: 2, difficulty: 'easy', difficulty_dots: 1,
    skill_tags: ['habit'], est_seconds: 60,
    goal: 'Build a daily habit with 3 quick items.',
    micro_tip: 'Consistency beats intensity.',
    screens: { intro: { headline: 'Streak Challenge', body: 'Three quick reps. Quiet progress.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Quick check: Child cries when asked to share. Most likely function?', options: ['Access', 'Escape/Avoid', 'Attention', 'Sensory/Body need'], answer: 'Access', explain: 'Crying is about keeping the item.' },
      { scenario: 'Quick check: "I can\'t do this!" and tears up paper. Escape or Attention?', options: ['Escape/Avoid', 'Attention'], answer: 'Escape/Avoid', explain: 'Tearing up the paper removes the demand.' },
      { scenario: 'Quick check: Best First-Then for a reluctant reader?', options: ['First: read 2 pages. Then: 5 min free choice.', 'First: read entire book. Then: maybe a reward.'], answer: 'First: read 2 pages. Then: 5 min free choice.', explain: 'Small, achievable First + immediate, preferred Then.' },
    ],
  },
  {
    id: 'pattern_cards', title: 'Pattern Cards', stage: 2, difficulty: 'easy', difficulty_dots: 1,
    skill_tags: ['retention'], est_seconds: 90,
    goal: 'Improve retention using spaced repetition.',
    micro_tip: 'Reviewing is a skill, not a setback.',
    screens: { intro: { headline: 'Pattern Cards', body: 'Quick retention reps. Calm, simple, effective.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'What are the 4 functions of behavior?', options: ['Attention, Escape, Access, Sensory', 'Happy, Sad, Angry, Scared'], answer: 'Attention, Escape, Access, Sensory', explain: 'The four functions explain WHY behavior happens.' },
      { scenario: 'What does ABC stand for?', options: ['Antecedent, Behavior, Consequence', 'Always Be Calm'], answer: 'Antecedent, Behavior, Consequence', explain: 'A = what happened before. B = observable behavior. C = what happened after.' },
      { scenario: 'What is reinforcement?', options: ['Anything that increases the likelihood of a behavior', 'A reward for good behavior'], answer: 'Anything that increases the likelihood of a behavior', explain: 'Reinforcement is not just rewards.' },
      { scenario: 'What is an extinction burst?', options: ['A temporary increase in behavior when reinforcement stops', 'When behavior disappears permanently'], answer: 'A temporary increase in behavior when reinforcement stops', explain: 'The brain tests harder before giving up.' },
      { scenario: 'What makes a good replacement skill?', options: ['Same function, easier to do, gets reinforced', 'Any appropriate behavior'], answer: 'Same function, easier to do, gets reinforced', explain: 'A replacement must serve the same function and be reinforced consistently.' },
      { scenario: 'Negative reinforcement means...', options: ['Removing something to increase behavior', 'Punishing bad behavior'], answer: 'Removing something to increase behavior', explain: 'Negative = removing. Reinforcement = increases behavior.' },
      { scenario: 'What is the difference between escape and avoidance?', options: ['Escape = after demand starts. Avoidance = before it starts.', 'They are the same thing.'], answer: 'Escape = after demand starts. Avoidance = before it starts.', explain: 'Escape removes an active demand. Avoidance prevents it from starting.' },
      { scenario: 'When should you use a visual timer?', options: ['During transitions and waiting periods', 'Only during punishment'], answer: 'During transitions and waiting periods', explain: 'Visual timers make time concrete and predictable.' },
      { scenario: 'What is intermittent reinforcement?', options: ['Reinforcing sometimes but not always', 'Reinforcing every single time'], answer: 'Reinforcing sometimes but not always', explain: 'Intermittent reinforcement makes behavior VERY resistant to change.' },
      { scenario: 'Best first step when behavior escalates?', options: ['Reduce demands and stay calm', 'Add more consequences immediately'], answer: 'Reduce demands and stay calm', explain: 'In crisis: fewer words, lower demands, calm presence.' },
    ],
  },
  {
    id: 'fix_the_plan', title: 'Fix the Plan', stage: 3, difficulty: 'hard', difficulty_dots: 4,
    skill_tags: ['planning'], est_seconds: 120,
    goal: 'Identify what is missing in a behavior plan.',
    micro_tip: 'A plan is only as strong as the reinforcement schedule.',
    screens: { intro: { headline: 'Fix the Plan', body: 'Advanced coaching reps: find what is missing fast.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Plan: Child hits for attention. Strategy: ignore hitting. What is missing?', options: ['A replacement skill to get attention', 'More punishment', 'A visual timer', 'A longer time-out'], answer: 'A replacement skill to get attention', explain: 'You can not just remove behavior without teaching what to do instead.' },
      { scenario: 'Plan: Teach child to ask for break. But breaks are never given when asked. What is missing?', options: ['Consistent reinforcement of the replacement', 'A different replacement skill', 'More consequences', 'A token board'], answer: 'Consistent reinforcement of the replacement', explain: 'If the new skill never works, the brain will not use it.' },
      { scenario: 'Plan: Tantrums at transitions. Strategy: rewards after calm transitions. No warning given. What is missing?', options: ['Antecedent strategy (warnings/timers)', 'More rewards', 'Punishment for tantrums', 'A new therapist'], answer: 'Antecedent strategy (warnings/timers)', explain: 'Plans need proactive strategies too - set up for success before the behavior happens.' },
      { scenario: 'Plan: Elopement from class. Strategy: verbal redirect each time. Elopement is escape-maintained. Missing?', options: ['Understanding that redirection may reinforce escape', 'Louder verbal redirects', 'A tracking chart', 'More recess time'], answer: 'Understanding that redirection may reinforce escape', explain: 'If the function is escape, verbal redirection may actually reinforce by providing a break from the task.' },
      { scenario: 'Plan: First-Then board. First: 10 pages reading. Then: 2 min free time. Child still refuses. Missing?', options: ['More reasonable First demand + more motivating Then', 'Remove the board', 'Punishment for refusal', 'A different board design'], answer: 'More reasonable First demand + more motivating Then', explain: '10 pages is too much and 2 minutes is not enough. The ratio needs to work for the learner.' },
      { scenario: 'Plan: "Help" card for escape behavior. Child uses card, aide says "try first." Missing?', options: ['Honoring the replacement skill initially', 'Taking the card away', 'Making them try harder', 'Adding a time-out'], answer: 'Honoring the replacement skill initially', explain: 'New replacement skills must be honored at first to compete with problem behavior.' },
      { scenario: 'Plan: Child bites for sensory input. Strategy: say "no biting" each time. Missing?', options: ['A sensory replacement (chewy, fidget)', 'More verbal corrections', 'Time-out', 'A reward chart'], answer: 'A sensory replacement (chewy, fidget)', explain: 'Sensory needs must be met. Verbal corrections do not address the underlying need.' },
      { scenario: 'Plan: Token board works. But backup reinforcer is not motivating. Missing?', options: ['A motivating backup reinforcer the child actually wants', 'More tokens required', 'Remove the token board', 'Consequences for not earning tokens'], answer: 'A motivating backup reinforcer the child actually wants', explain: 'The whole system fails if the end reward is not worth working for.' },
    ],
  },
  {
    id: 'generalization_quest', title: 'Generalization Quest', stage: 2, difficulty: 'med', difficulty_dots: 3,
    skill_tags: ['generalization'], est_seconds: 120,
    goal: 'Choose the best next step to generalize a skill.',
    micro_tip: 'Change one variable at a time when generalizing.',
    screens: { intro: { headline: 'Generalization Quest', body: 'Practice planning how skills transfer to new settings.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child asks for break at home with mom. Now what?', options: ['Practice asking for break at school with teacher', 'Practice 10 new skills at once', 'Stop teaching - they got it', 'Only practice at home forever'], answer: 'Practice asking for break at school with teacher', explain: 'Change one variable (setting/person) at a time. Keep reinforcement high.' },
      { scenario: 'Student raises hand in math class. Goal: generalize to other classes.', options: ['Practice hand-raising in one new class at a time', 'Expect it in all classes immediately', 'Only reinforce in math class', 'Remove all support'], answer: 'Practice hand-raising in one new class at a time', explain: 'Gradual expansion: one new setting at a time with continued reinforcement.' },
      { scenario: 'Child uses "help" card with therapist. Goal: use with parents.', options: ['Have parents practice with the same card + prompts', 'Give parents a different card', 'Stop therapist sessions', 'Wait for it to happen naturally'], answer: 'Have parents practice with the same card + prompts', explain: 'Same tool, new person, with support. Change one variable at a time.' },
      { scenario: 'Learner tolerates waiting 30 seconds. Goal: longer waits.', options: ['Gradually increase to 45 seconds, then 60', 'Jump to 5 minutes immediately', 'Celebrate and stop practicing', 'Only practice at home'], answer: 'Gradually increase to 45 seconds, then 60', explain: 'Gradual shaping: small increments with reinforcement at each step.' },
      { scenario: 'Child uses calm voice at school. At home, still yells.', options: ['Teach and reinforce calm voice at home using same strategy', 'Punish yelling at home', 'Accept that school and home are different', 'Stop school support'], answer: 'Teach and reinforce calm voice at home using same strategy', explain: 'Skills do not automatically transfer. Actively teach in the new environment.' },
      { scenario: 'Child greets teacher every morning. Goal: greet other adults.', options: ['Practice greeting one new adult at a time with prompts', 'Expect greeting all adults immediately', 'Only greet the teacher', 'Remove all prompts immediately'], answer: 'Practice greeting one new adult at a time with prompts', explain: 'Expand gradually. Prompts and reinforcement support generalization.' },
      { scenario: 'Learner follows 1-step directions from mom. Dad wants the same.', options: ['Dad uses same language and reinforcement strategy', 'Dad uses completely different approach', 'Only practice with mom', 'Stop giving directions'], answer: 'Dad uses same language and reinforcement strategy', explain: 'Consistency in language and reinforcement across people aids generalization.' },
      { scenario: 'Child eats new foods at school but not home. What helps?', options: ['Replicate the school mealtime setup at home initially', 'Force new foods at home', 'Only serve new foods at school', 'Give up on home meals'], answer: 'Replicate the school mealtime setup at home initially', explain: 'Match the successful conditions first, then gradually make them more natural.' },
    ],
  },
  {
    id: 'maintenance_check', title: 'Maintenance Check', stage: 3, difficulty: 'hard', difficulty_dots: 4,
    skill_tags: ['planning'], est_seconds: 120,
    goal: 'Ensure skills are maintained over time.',
    micro_tip: 'Maintenance means the skill still works when supports are faded.',
    screens: { intro: { headline: 'Maintenance Check', body: 'Practice keeping progress going after initial success.', cta: 'Start' }, results: { buttons: ['Try again', 'Next drill', 'Back to Lab'] } },
    questions: [
      { scenario: 'Child has used break card for 3 weeks. Team wants to stop prompting. Best approach?', options: ['Fade prompts gradually: delay by 3 sec, then 5, then remove', 'Stop prompting all at once', 'Keep prompting forever', 'Remove the break card entirely'], answer: 'Fade prompts gradually: delay by 3 sec, then 5, then remove', explain: 'Gradual fading maintains the skill while building independence.' },
      { scenario: 'Behavior improved for 2 weeks. Team wants to stop the plan. What should they do?', options: ['Continue plan but thin reinforcement gradually', 'Stop the plan completely', 'Keep everything the same forever', 'Add more consequences'], answer: 'Continue plan but thin reinforcement gradually', explain: 'Thin the schedule (reinforce less often) rather than stopping abruptly.' },
      { scenario: 'Learner\'s skill fades during school break. What happened?', options: ['Skill was not practiced/reinforced during break', 'The plan never worked', 'The child chose to regress', 'This is normal and fine to ignore'], answer: 'Skill was not practiced/reinforced during break', explain: 'Skills need continued practice and reinforcement. Breaks cause regression.' },
      { scenario: 'Token board worked great for 1 month. Now child is bored. What to do?', options: ['Update the backup reinforcer menu', 'Stop using tokens', 'Double the tokens required', 'Punish disinterest'], answer: 'Update the backup reinforcer menu', explain: 'Reinforcers lose value over time (satiation). Rotate and offer fresh choices.' },
      { scenario: 'Child generalized a skill to 3 settings. How to maintain?', options: ['Check in periodically and reinforce across all settings', 'Assume it will maintain on its own', 'Only reinforce in the original setting', 'Stop all reinforcement immediately'], answer: 'Check in periodically and reinforce across all settings', explain: 'Periodic checks + intermittent reinforcement maintains generalization.' },
      { scenario: 'Parent: "We have been doing great, so I stopped the visual schedule." Behavior returned. Why?', options: ['Schedule was still needed - remove supports gradually', 'Child is choosing to misbehave', 'Schedule never really worked', 'This was inevitable'], answer: 'Schedule was still needed - remove supports gradually', explain: 'Supports should be faded systematically, not dropped once things improve.' },
    ],
  },
];
